// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: sandbox.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxAgent_Health_FullMethodName                = "/sandbox.v1.SandboxAgent/Health"
	SandboxAgent_CreateSandbox_FullMethodName         = "/sandbox.v1.SandboxAgent/CreateSandbox"
	SandboxAgent_GetSandbox_FullMethodName            = "/sandbox.v1.SandboxAgent/GetSandbox"
	SandboxAgent_DeleteSandbox_FullMethodName         = "/sandbox.v1.SandboxAgent/DeleteSandbox"
	SandboxAgent_ListSandboxes_FullMethodName         = "/sandbox.v1.SandboxAgent/ListSandboxes"
	SandboxAgent_UpdateSandboxActivity_FullMethodName = "/sandbox.v1.SandboxAgent/UpdateSandboxActivity"
	SandboxAgent_SuspendSandbox_FullMethodName        = "/sandbox.v1.SandboxAgent/SuspendSandbox"
	SandboxAgent_Exec_FullMethodName                  = "/sandbox.v1.SandboxAgent/Exec"
	SandboxAgent_StartProcess_FullMethodName          = "/sandbox.v1.SandboxAgent/StartProcess"
	SandboxAgent_WriteToProcess_FullMethodName        = "/sandbox.v1.SandboxAgent/WriteToProcess"
	SandboxAgent_ReadProcessStdout_FullMethodName     = "/sandbox.v1.SandboxAgent/ReadProcessStdout"
	SandboxAgent_ReadProcessStderr_FullMethodName     = "/sandbox.v1.SandboxAgent/ReadProcessStderr"
	SandboxAgent_CloseProcessStdin_FullMethodName     = "/sandbox.v1.SandboxAgent/CloseProcessStdin"
	SandboxAgent_KillProcess_FullMethodName           = "/sandbox.v1.SandboxAgent/KillProcess"
	SandboxAgent_WaitProcess_FullMethodName           = "/sandbox.v1.SandboxAgent/WaitProcess"
	SandboxAgent_ResizeTerminal_FullMethodName        = "/sandbox.v1.SandboxAgent/ResizeTerminal"
	SandboxAgent_StreamProcessOutput_FullMethodName   = "/sandbox.v1.SandboxAgent/StreamProcessOutput"
	SandboxAgent_ReadFile_FullMethodName              = "/sandbox.v1.SandboxAgent/ReadFile"
	SandboxAgent_WriteFile_FullMethodName             = "/sandbox.v1.SandboxAgent/WriteFile"
	SandboxAgent_ReadArchive_FullMethodName           = "/sandbox.v1.SandboxAgent/ReadArchive"
	SandboxAgent_WriteArchive_FullMethodName          = "/sandbox.v1.SandboxAgent/WriteArchive"
	SandboxAgent_SaveVMState_FullMethodName           = "/sandbox.v1.SandboxAgent/SaveVMState"
	SandboxAgent_RestoreVMState_FullMethodName        = "/sandbox.v1.SandboxAgent/RestoreVMState"
)

// SandboxAgentClient is the client API for SandboxAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxAgentClient interface {
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// Sandbox lifecycle management
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	UpdateSandboxActivity(ctx context.Context, in *UpdateSandboxActivityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SuspendSandbox snapshots the sandbox's /data directory, uploads to S3, and deletes the pod.
	// Only supported in pod mode with storage enabled.
	SuspendSandbox(ctx context.Context, in *SuspendSandboxRequest, opts ...grpc.CallOption) (*SuspendSandboxResponse, error)
	// Command execution
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// Process management (interactive/streaming)
	StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error)
	WriteToProcess(ctx context.Context, in *WriteToProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadProcessStdout(ctx context.Context, in *ReadProcessOutputRequest, opts ...grpc.CallOption) (*ReadProcessOutputResponse, error)
	ReadProcessStderr(ctx context.Context, in *ReadProcessOutputRequest, opts ...grpc.CallOption) (*ReadProcessOutputResponse, error)
	CloseProcessStdin(ctx context.Context, in *CloseProcessStdinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc.CallOption) (*WaitProcessResponse, error)
	ResizeTerminal(ctx context.Context, in *ResizeTerminalRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// StreamProcessOutput streams stdout and stderr from a process in real-time.
	// This is more efficient than polling ReadProcessStdout/ReadProcessStderr.
	StreamProcessOutput(ctx context.Context, in *StreamProcessOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessOutputChunk], error)
	// File operations
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadArchive(ctx context.Context, in *ReadArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArchiveChunk], error)
	WriteArchive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteArchiveRequest, WriteArchiveResponse], error)
	// VM state management (kata mode only)
	SaveVMState(ctx context.Context, in *SaveVMStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RestoreVMState(ctx context.Context, in *RestoreVMStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sandboxAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxAgentClient(cc grpc.ClientConnInterface) SandboxAgentClient {
	return &sandboxAgentClient{cc}
}

func (c *sandboxAgentClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, SandboxAgent_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, SandboxAgent_GetSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_DeleteSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) UpdateSandboxActivity(ctx context.Context, in *UpdateSandboxActivityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_UpdateSandboxActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) SuspendSandbox(ctx context.Context, in *SuspendSandboxRequest, opts ...grpc.CallOption) (*SuspendSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_SuspendSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartProcessResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_StartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) WriteToProcess(ctx context.Context, in *WriteToProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_WriteToProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ReadProcessStdout(ctx context.Context, in *ReadProcessOutputRequest, opts ...grpc.CallOption) (*ReadProcessOutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadProcessOutputResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ReadProcessStdout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ReadProcessStderr(ctx context.Context, in *ReadProcessOutputRequest, opts ...grpc.CallOption) (*ReadProcessOutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadProcessOutputResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ReadProcessStderr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) CloseProcessStdin(ctx context.Context, in *CloseProcessStdinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_CloseProcessStdin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc.CallOption) (*WaitProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitProcessResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_WaitProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ResizeTerminal(ctx context.Context, in *ResizeTerminalRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_ResizeTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) StreamProcessOutput(ctx context.Context, in *StreamProcessOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessOutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxAgent_ServiceDesc.Streams[0], SandboxAgent_StreamProcessOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamProcessOutputRequest, ProcessOutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_StreamProcessOutputClient = grpc.ServerStreamingClient[ProcessOutputChunk]

func (c *sandboxAgentClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ReadArchive(ctx context.Context, in *ReadArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArchiveChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxAgent_ServiceDesc.Streams[1], SandboxAgent_ReadArchive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadArchiveRequest, ArchiveChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ReadArchiveClient = grpc.ServerStreamingClient[ArchiveChunk]

func (c *sandboxAgentClient) WriteArchive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteArchiveRequest, WriteArchiveResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxAgent_ServiceDesc.Streams[2], SandboxAgent_WriteArchive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteArchiveRequest, WriteArchiveResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_WriteArchiveClient = grpc.ClientStreamingClient[WriteArchiveRequest, WriteArchiveResponse]

func (c *sandboxAgentClient) SaveVMState(ctx context.Context, in *SaveVMStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_SaveVMState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) RestoreVMState(ctx context.Context, in *RestoreVMStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_RestoreVMState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxAgentServer is the server API for SandboxAgent service.
// All implementations must embed UnimplementedSandboxAgentServer
// for forward compatibility.
type SandboxAgentServer interface {
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	// Sandbox lifecycle management
	CreateSandbox(context.Context, *CreateSandboxRequest) (*SandboxInfo, error)
	GetSandbox(context.Context, *GetSandboxRequest) (*SandboxInfo, error)
	DeleteSandbox(context.Context, *DeleteSandboxRequest) (*emptypb.Empty, error)
	ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	UpdateSandboxActivity(context.Context, *UpdateSandboxActivityRequest) (*emptypb.Empty, error)
	// SuspendSandbox snapshots the sandbox's /data directory, uploads to S3, and deletes the pod.
	// Only supported in pod mode with storage enabled.
	SuspendSandbox(context.Context, *SuspendSandboxRequest) (*SuspendSandboxResponse, error)
	// Command execution
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// Process management (interactive/streaming)
	StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error)
	WriteToProcess(context.Context, *WriteToProcessRequest) (*emptypb.Empty, error)
	ReadProcessStdout(context.Context, *ReadProcessOutputRequest) (*ReadProcessOutputResponse, error)
	ReadProcessStderr(context.Context, *ReadProcessOutputRequest) (*ReadProcessOutputResponse, error)
	CloseProcessStdin(context.Context, *CloseProcessStdinRequest) (*emptypb.Empty, error)
	KillProcess(context.Context, *KillProcessRequest) (*emptypb.Empty, error)
	WaitProcess(context.Context, *WaitProcessRequest) (*WaitProcessResponse, error)
	ResizeTerminal(context.Context, *ResizeTerminalRequest) (*emptypb.Empty, error)
	// StreamProcessOutput streams stdout and stderr from a process in real-time.
	// This is more efficient than polling ReadProcessStdout/ReadProcessStderr.
	StreamProcessOutput(*StreamProcessOutputRequest, grpc.ServerStreamingServer[ProcessOutputChunk]) error
	// File operations
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*emptypb.Empty, error)
	ReadArchive(*ReadArchiveRequest, grpc.ServerStreamingServer[ArchiveChunk]) error
	WriteArchive(grpc.ClientStreamingServer[WriteArchiveRequest, WriteArchiveResponse]) error
	// VM state management (kata mode only)
	SaveVMState(context.Context, *SaveVMStateRequest) (*emptypb.Empty, error)
	RestoreVMState(context.Context, *RestoreVMStateRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSandboxAgentServer()
}

// UnimplementedSandboxAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxAgentServer struct{}

func (UnimplementedSandboxAgentServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSandboxAgentServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedSandboxAgentServer) GetSandbox(context.Context, *GetSandboxRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedSandboxAgentServer) DeleteSandbox(context.Context, *DeleteSandboxRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (UnimplementedSandboxAgentServer) ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedSandboxAgentServer) UpdateSandboxActivity(context.Context, *UpdateSandboxActivityRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSandboxActivity not implemented")
}
func (UnimplementedSandboxAgentServer) SuspendSandbox(context.Context, *SuspendSandboxRequest) (*SuspendSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendSandbox not implemented")
}
func (UnimplementedSandboxAgentServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxAgentServer) StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartProcess not implemented")
}
func (UnimplementedSandboxAgentServer) WriteToProcess(context.Context, *WriteToProcessRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteToProcess not implemented")
}
func (UnimplementedSandboxAgentServer) ReadProcessStdout(context.Context, *ReadProcessOutputRequest) (*ReadProcessOutputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadProcessStdout not implemented")
}
func (UnimplementedSandboxAgentServer) ReadProcessStderr(context.Context, *ReadProcessOutputRequest) (*ReadProcessOutputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadProcessStderr not implemented")
}
func (UnimplementedSandboxAgentServer) CloseProcessStdin(context.Context, *CloseProcessStdinRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseProcessStdin not implemented")
}
func (UnimplementedSandboxAgentServer) KillProcess(context.Context, *KillProcessRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedSandboxAgentServer) WaitProcess(context.Context, *WaitProcessRequest) (*WaitProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitProcess not implemented")
}
func (UnimplementedSandboxAgentServer) ResizeTerminal(context.Context, *ResizeTerminalRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeTerminal not implemented")
}
func (UnimplementedSandboxAgentServer) StreamProcessOutput(*StreamProcessOutputRequest, grpc.ServerStreamingServer[ProcessOutputChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamProcessOutput not implemented")
}
func (UnimplementedSandboxAgentServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSandboxAgentServer) WriteFile(context.Context, *WriteFileRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSandboxAgentServer) ReadArchive(*ReadArchiveRequest, grpc.ServerStreamingServer[ArchiveChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadArchive not implemented")
}
func (UnimplementedSandboxAgentServer) WriteArchive(grpc.ClientStreamingServer[WriteArchiveRequest, WriteArchiveResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteArchive not implemented")
}
func (UnimplementedSandboxAgentServer) SaveVMState(context.Context, *SaveVMStateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveVMState not implemented")
}
func (UnimplementedSandboxAgentServer) RestoreVMState(context.Context, *RestoreVMStateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreVMState not implemented")
}
func (UnimplementedSandboxAgentServer) mustEmbedUnimplementedSandboxAgentServer() {}
func (UnimplementedSandboxAgentServer) testEmbeddedByValue()                      {}

// UnsafeSandboxAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxAgentServer will
// result in compilation errors.
type UnsafeSandboxAgentServer interface {
	mustEmbedUnimplementedSandboxAgentServer()
}

func RegisterSandboxAgentServer(s grpc.ServiceRegistrar, srv SandboxAgentServer) {
	// If the following call panics, it indicates UnimplementedSandboxAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxAgent_ServiceDesc, srv)
}

func _SandboxAgent_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).GetSandbox(ctx, req.(*GetSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_DeleteSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).DeleteSandbox(ctx, req.(*DeleteSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ListSandboxes(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_UpdateSandboxActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSandboxActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).UpdateSandboxActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_UpdateSandboxActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).UpdateSandboxActivity(ctx, req.(*UpdateSandboxActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_SuspendSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SuspendSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SuspendSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SuspendSandbox(ctx, req.(*SuspendSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_StartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).StartProcess(ctx, req.(*StartProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_WriteToProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteToProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).WriteToProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_WriteToProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).WriteToProcess(ctx, req.(*WriteToProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ReadProcessStdout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProcessOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ReadProcessStdout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ReadProcessStdout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ReadProcessStdout(ctx, req.(*ReadProcessOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ReadProcessStderr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProcessOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ReadProcessStderr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ReadProcessStderr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ReadProcessStderr(ctx, req.(*ReadProcessOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_CloseProcessStdin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseProcessStdinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).CloseProcessStdin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_CloseProcessStdin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).CloseProcessStdin(ctx, req.(*CloseProcessStdinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).KillProcess(ctx, req.(*KillProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_WaitProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).WaitProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_WaitProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).WaitProcess(ctx, req.(*WaitProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ResizeTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ResizeTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ResizeTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ResizeTerminal(ctx, req.(*ResizeTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_StreamProcessOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProcessOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxAgentServer).StreamProcessOutput(m, &grpc.GenericServerStream[StreamProcessOutputRequest, ProcessOutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_StreamProcessOutputServer = grpc.ServerStreamingServer[ProcessOutputChunk]

func _SandboxAgent_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ReadArchive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadArchiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxAgentServer).ReadArchive(m, &grpc.GenericServerStream[ReadArchiveRequest, ArchiveChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ReadArchiveServer = grpc.ServerStreamingServer[ArchiveChunk]

func _SandboxAgent_WriteArchive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxAgentServer).WriteArchive(&grpc.GenericServerStream[WriteArchiveRequest, WriteArchiveResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_WriteArchiveServer = grpc.ClientStreamingServer[WriteArchiveRequest, WriteArchiveResponse]

func _SandboxAgent_SaveVMState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveVMStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SaveVMState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SaveVMState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SaveVMState(ctx, req.(*SaveVMStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_RestoreVMState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreVMStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).RestoreVMState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_RestoreVMState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).RestoreVMState(ctx, req.(*RestoreVMStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxAgent_ServiceDesc is the grpc.ServiceDesc for SandboxAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.v1.SandboxAgent",
	HandlerType: (*SandboxAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _SandboxAgent_Health_Handler,
		},
		{
			MethodName: "CreateSandbox",
			Handler:    _SandboxAgent_CreateSandbox_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _SandboxAgent_GetSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _SandboxAgent_DeleteSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _SandboxAgent_ListSandboxes_Handler,
		},
		{
			MethodName: "UpdateSandboxActivity",
			Handler:    _SandboxAgent_UpdateSandboxActivity_Handler,
		},
		{
			MethodName: "SuspendSandbox",
			Handler:    _SandboxAgent_SuspendSandbox_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _SandboxAgent_Exec_Handler,
		},
		{
			MethodName: "StartProcess",
			Handler:    _SandboxAgent_StartProcess_Handler,
		},
		{
			MethodName: "WriteToProcess",
			Handler:    _SandboxAgent_WriteToProcess_Handler,
		},
		{
			MethodName: "ReadProcessStdout",
			Handler:    _SandboxAgent_ReadProcessStdout_Handler,
		},
		{
			MethodName: "ReadProcessStderr",
			Handler:    _SandboxAgent_ReadProcessStderr_Handler,
		},
		{
			MethodName: "CloseProcessStdin",
			Handler:    _SandboxAgent_CloseProcessStdin_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _SandboxAgent_KillProcess_Handler,
		},
		{
			MethodName: "WaitProcess",
			Handler:    _SandboxAgent_WaitProcess_Handler,
		},
		{
			MethodName: "ResizeTerminal",
			Handler:    _SandboxAgent_ResizeTerminal_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _SandboxAgent_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _SandboxAgent_WriteFile_Handler,
		},
		{
			MethodName: "SaveVMState",
			Handler:    _SandboxAgent_SaveVMState_Handler,
		},
		{
			MethodName: "RestoreVMState",
			Handler:    _SandboxAgent_RestoreVMState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProcessOutput",
			Handler:       _SandboxAgent_StreamProcessOutput_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadArchive",
			Handler:       _SandboxAgent_ReadArchive_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteArchive",
			Handler:       _SandboxAgent_WriteArchive_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sandbox.proto",
}
