// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: sandbox.proto

package pb

import (
	context "context"
	protocols "github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols"
	grpc1 "github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols/grpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxAgent_Health_FullMethodName                = "/sandbox.v1.SandboxAgent/Health"
	SandboxAgent_ListVMs_FullMethodName               = "/sandbox.v1.SandboxAgent/ListVMs"
	SandboxAgent_Exec_FullMethodName                  = "/sandbox.v1.SandboxAgent/Exec"
	SandboxAgent_SaveVMState_FullMethodName           = "/sandbox.v1.SandboxAgent/SaveVMState"
	SandboxAgent_RestoreVMState_FullMethodName        = "/sandbox.v1.SandboxAgent/RestoreVMState"
	SandboxAgent_CreateContainer_FullMethodName       = "/sandbox.v1.SandboxAgent/CreateContainer"
	SandboxAgent_StartContainer_FullMethodName        = "/sandbox.v1.SandboxAgent/StartContainer"
	SandboxAgent_RemoveContainer_FullMethodName       = "/sandbox.v1.SandboxAgent/RemoveContainer"
	SandboxAgent_ExecProcess_FullMethodName           = "/sandbox.v1.SandboxAgent/ExecProcess"
	SandboxAgent_SignalProcess_FullMethodName         = "/sandbox.v1.SandboxAgent/SignalProcess"
	SandboxAgent_WaitProcess_FullMethodName           = "/sandbox.v1.SandboxAgent/WaitProcess"
	SandboxAgent_UpdateContainer_FullMethodName       = "/sandbox.v1.SandboxAgent/UpdateContainer"
	SandboxAgent_UpdateEphemeralMounts_FullMethodName = "/sandbox.v1.SandboxAgent/UpdateEphemeralMounts"
	SandboxAgent_StatsContainer_FullMethodName        = "/sandbox.v1.SandboxAgent/StatsContainer"
	SandboxAgent_PauseContainer_FullMethodName        = "/sandbox.v1.SandboxAgent/PauseContainer"
	SandboxAgent_ResumeContainer_FullMethodName       = "/sandbox.v1.SandboxAgent/ResumeContainer"
	SandboxAgent_WriteStdin_FullMethodName            = "/sandbox.v1.SandboxAgent/WriteStdin"
	SandboxAgent_ReadStdout_FullMethodName            = "/sandbox.v1.SandboxAgent/ReadStdout"
	SandboxAgent_ReadStderr_FullMethodName            = "/sandbox.v1.SandboxAgent/ReadStderr"
	SandboxAgent_CloseStdin_FullMethodName            = "/sandbox.v1.SandboxAgent/CloseStdin"
	SandboxAgent_TtyWinResize_FullMethodName          = "/sandbox.v1.SandboxAgent/TtyWinResize"
	SandboxAgent_UpdateInterface_FullMethodName       = "/sandbox.v1.SandboxAgent/UpdateInterface"
	SandboxAgent_UpdateRoutes_FullMethodName          = "/sandbox.v1.SandboxAgent/UpdateRoutes"
	SandboxAgent_ListInterfaces_FullMethodName        = "/sandbox.v1.SandboxAgent/ListInterfaces"
	SandboxAgent_ListRoutes_FullMethodName            = "/sandbox.v1.SandboxAgent/ListRoutes"
	SandboxAgent_AddARPNeighbors_FullMethodName       = "/sandbox.v1.SandboxAgent/AddARPNeighbors"
	SandboxAgent_GetIPTables_FullMethodName           = "/sandbox.v1.SandboxAgent/GetIPTables"
	SandboxAgent_SetIPTables_FullMethodName           = "/sandbox.v1.SandboxAgent/SetIPTables"
	SandboxAgent_GetMetrics_FullMethodName            = "/sandbox.v1.SandboxAgent/GetMetrics"
	SandboxAgent_MemAgentMemcgSet_FullMethodName      = "/sandbox.v1.SandboxAgent/MemAgentMemcgSet"
	SandboxAgent_MemAgentCompactSet_FullMethodName    = "/sandbox.v1.SandboxAgent/MemAgentCompactSet"
	SandboxAgent_SetGuestDateTime_FullMethodName      = "/sandbox.v1.SandboxAgent/SetGuestDateTime"
	SandboxAgent_CopyFile_FullMethodName              = "/sandbox.v1.SandboxAgent/CopyFile"
	SandboxAgent_GetVolumeStats_FullMethodName        = "/sandbox.v1.SandboxAgent/GetVolumeStats"
	SandboxAgent_ResizeVolume_FullMethodName          = "/sandbox.v1.SandboxAgent/ResizeVolume"
)

// SandboxAgentClient is the client API for SandboxAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxAgentClient interface {
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	SaveVMState(ctx context.Context, in *SaveVMStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RestoreVMState(ctx context.Context, in *RestoreVMStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ExecProcess(ctx context.Context, in *ExecProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc.CallOption) (*grpc1.WaitProcessResponse, error)
	UpdateContainer(ctx context.Context, in *UpdateContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateEphemeralMounts(ctx context.Context, in *UpdateEphemeralMountsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StatsContainer(ctx context.Context, in *StatsContainerRequest, opts ...grpc.CallOption) (*grpc1.StatsContainerResponse, error)
	PauseContainer(ctx context.Context, in *PauseContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResumeContainer(ctx context.Context, in *ResumeContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	WriteStdin(ctx context.Context, in *WriteStdinRequest, opts ...grpc.CallOption) (*grpc1.WriteStreamResponse, error)
	ReadStdout(ctx context.Context, in *ReadStdoutRequest, opts ...grpc.CallOption) (*grpc1.ReadStreamResponse, error)
	ReadStderr(ctx context.Context, in *ReadStderrRequest, opts ...grpc.CallOption) (*grpc1.ReadStreamResponse, error)
	CloseStdin(ctx context.Context, in *CloseStdinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TtyWinResize(ctx context.Context, in *TtyWinResizeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateInterface(ctx context.Context, in *UpdateInterfaceRequest, opts ...grpc.CallOption) (*protocols.Interface, error)
	UpdateRoutes(ctx context.Context, in *UpdateRoutesRequest, opts ...grpc.CallOption) (*grpc1.Routes, error)
	ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*grpc1.Interfaces, error)
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*grpc1.Routes, error)
	AddARPNeighbors(ctx context.Context, in *AddARPNeighborsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetIPTables(ctx context.Context, in *GetIPTablesRequest, opts ...grpc.CallOption) (*grpc1.GetIPTablesResponse, error)
	SetIPTables(ctx context.Context, in *SetIPTablesRequest, opts ...grpc.CallOption) (*grpc1.SetIPTablesResponse, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*grpc1.Metrics, error)
	MemAgentMemcgSet(ctx context.Context, in *MemAgentMemcgSetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MemAgentCompactSet(ctx context.Context, in *MemAgentCompactSetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetGuestDateTime(ctx context.Context, in *SetGuestDateTimeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetVolumeStats(ctx context.Context, in *GetVolumeStatsRequest, opts ...grpc.CallOption) (*grpc1.VolumeStatsResponse, error)
	ResizeVolume(ctx context.Context, in *ResizeVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sandboxAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxAgentClient(cc grpc.ClientConnInterface) SandboxAgentClient {
	return &sandboxAgentClient{cc}
}

func (c *sandboxAgentClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) SaveVMState(ctx context.Context, in *SaveVMStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_SaveVMState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) RestoreVMState(ctx context.Context, in *RestoreVMStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_RestoreVMState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_CreateContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_StartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_RemoveContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ExecProcess(ctx context.Context, in *ExecProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_ExecProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) SignalProcess(ctx context.Context, in *SignalProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_SignalProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc.CallOption) (*grpc1.WaitProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.WaitProcessResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_WaitProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) UpdateContainer(ctx context.Context, in *UpdateContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_UpdateContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) UpdateEphemeralMounts(ctx context.Context, in *UpdateEphemeralMountsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_UpdateEphemeralMounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) StatsContainer(ctx context.Context, in *StatsContainerRequest, opts ...grpc.CallOption) (*grpc1.StatsContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.StatsContainerResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_StatsContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) PauseContainer(ctx context.Context, in *PauseContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_PauseContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ResumeContainer(ctx context.Context, in *ResumeContainerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_ResumeContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) WriteStdin(ctx context.Context, in *WriteStdinRequest, opts ...grpc.CallOption) (*grpc1.WriteStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.WriteStreamResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_WriteStdin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ReadStdout(ctx context.Context, in *ReadStdoutRequest, opts ...grpc.CallOption) (*grpc1.ReadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.ReadStreamResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ReadStdout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ReadStderr(ctx context.Context, in *ReadStderrRequest, opts ...grpc.CallOption) (*grpc1.ReadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.ReadStreamResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ReadStderr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) CloseStdin(ctx context.Context, in *CloseStdinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_CloseStdin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) TtyWinResize(ctx context.Context, in *TtyWinResizeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_TtyWinResize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) UpdateInterface(ctx context.Context, in *UpdateInterfaceRequest, opts ...grpc.CallOption) (*protocols.Interface, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(protocols.Interface)
	err := c.cc.Invoke(ctx, SandboxAgent_UpdateInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) UpdateRoutes(ctx context.Context, in *UpdateRoutesRequest, opts ...grpc.CallOption) (*grpc1.Routes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.Routes)
	err := c.cc.Invoke(ctx, SandboxAgent_UpdateRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*grpc1.Interfaces, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.Interfaces)
	err := c.cc.Invoke(ctx, SandboxAgent_ListInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*grpc1.Routes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.Routes)
	err := c.cc.Invoke(ctx, SandboxAgent_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) AddARPNeighbors(ctx context.Context, in *AddARPNeighborsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_AddARPNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) GetIPTables(ctx context.Context, in *GetIPTablesRequest, opts ...grpc.CallOption) (*grpc1.GetIPTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.GetIPTablesResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_GetIPTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) SetIPTables(ctx context.Context, in *SetIPTablesRequest, opts ...grpc.CallOption) (*grpc1.SetIPTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.SetIPTablesResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_SetIPTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*grpc1.Metrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.Metrics)
	err := c.cc.Invoke(ctx, SandboxAgent_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) MemAgentMemcgSet(ctx context.Context, in *MemAgentMemcgSetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_MemAgentMemcgSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) MemAgentCompactSet(ctx context.Context, in *MemAgentCompactSetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_MemAgentCompactSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) SetGuestDateTime(ctx context.Context, in *SetGuestDateTimeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_SetGuestDateTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_CopyFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) GetVolumeStats(ctx context.Context, in *GetVolumeStatsRequest, opts ...grpc.CallOption) (*grpc1.VolumeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(grpc1.VolumeStatsResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_GetVolumeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ResizeVolume(ctx context.Context, in *ResizeVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SandboxAgent_ResizeVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxAgentServer is the server API for SandboxAgent service.
// All implementations must embed UnimplementedSandboxAgentServer
// for forward compatibility.
type SandboxAgentServer interface {
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	SaveVMState(context.Context, *SaveVMStateRequest) (*emptypb.Empty, error)
	RestoreVMState(context.Context, *RestoreVMStateRequest) (*emptypb.Empty, error)
	CreateContainer(context.Context, *CreateContainerRequest) (*emptypb.Empty, error)
	StartContainer(context.Context, *StartContainerRequest) (*emptypb.Empty, error)
	RemoveContainer(context.Context, *RemoveContainerRequest) (*emptypb.Empty, error)
	ExecProcess(context.Context, *ExecProcessRequest) (*emptypb.Empty, error)
	SignalProcess(context.Context, *SignalProcessRequest) (*emptypb.Empty, error)
	WaitProcess(context.Context, *WaitProcessRequest) (*grpc1.WaitProcessResponse, error)
	UpdateContainer(context.Context, *UpdateContainerRequest) (*emptypb.Empty, error)
	UpdateEphemeralMounts(context.Context, *UpdateEphemeralMountsRequest) (*emptypb.Empty, error)
	StatsContainer(context.Context, *StatsContainerRequest) (*grpc1.StatsContainerResponse, error)
	PauseContainer(context.Context, *PauseContainerRequest) (*emptypb.Empty, error)
	ResumeContainer(context.Context, *ResumeContainerRequest) (*emptypb.Empty, error)
	WriteStdin(context.Context, *WriteStdinRequest) (*grpc1.WriteStreamResponse, error)
	ReadStdout(context.Context, *ReadStdoutRequest) (*grpc1.ReadStreamResponse, error)
	ReadStderr(context.Context, *ReadStderrRequest) (*grpc1.ReadStreamResponse, error)
	CloseStdin(context.Context, *CloseStdinRequest) (*emptypb.Empty, error)
	TtyWinResize(context.Context, *TtyWinResizeRequest) (*emptypb.Empty, error)
	UpdateInterface(context.Context, *UpdateInterfaceRequest) (*protocols.Interface, error)
	UpdateRoutes(context.Context, *UpdateRoutesRequest) (*grpc1.Routes, error)
	ListInterfaces(context.Context, *ListInterfacesRequest) (*grpc1.Interfaces, error)
	ListRoutes(context.Context, *ListRoutesRequest) (*grpc1.Routes, error)
	AddARPNeighbors(context.Context, *AddARPNeighborsRequest) (*emptypb.Empty, error)
	GetIPTables(context.Context, *GetIPTablesRequest) (*grpc1.GetIPTablesResponse, error)
	SetIPTables(context.Context, *SetIPTablesRequest) (*grpc1.SetIPTablesResponse, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*grpc1.Metrics, error)
	MemAgentMemcgSet(context.Context, *MemAgentMemcgSetRequest) (*emptypb.Empty, error)
	MemAgentCompactSet(context.Context, *MemAgentCompactSetRequest) (*emptypb.Empty, error)
	SetGuestDateTime(context.Context, *SetGuestDateTimeRequest) (*emptypb.Empty, error)
	CopyFile(context.Context, *CopyFileRequest) (*emptypb.Empty, error)
	GetVolumeStats(context.Context, *GetVolumeStatsRequest) (*grpc1.VolumeStatsResponse, error)
	ResizeVolume(context.Context, *ResizeVolumeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSandboxAgentServer()
}

// UnimplementedSandboxAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxAgentServer struct{}

func (UnimplementedSandboxAgentServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSandboxAgentServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedSandboxAgentServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxAgentServer) SaveVMState(context.Context, *SaveVMStateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveVMState not implemented")
}
func (UnimplementedSandboxAgentServer) RestoreVMState(context.Context, *RestoreVMStateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreVMState not implemented")
}
func (UnimplementedSandboxAgentServer) CreateContainer(context.Context, *CreateContainerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateContainer not implemented")
}
func (UnimplementedSandboxAgentServer) StartContainer(context.Context, *StartContainerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartContainer not implemented")
}
func (UnimplementedSandboxAgentServer) RemoveContainer(context.Context, *RemoveContainerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveContainer not implemented")
}
func (UnimplementedSandboxAgentServer) ExecProcess(context.Context, *ExecProcessRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecProcess not implemented")
}
func (UnimplementedSandboxAgentServer) SignalProcess(context.Context, *SignalProcessRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalProcess not implemented")
}
func (UnimplementedSandboxAgentServer) WaitProcess(context.Context, *WaitProcessRequest) (*grpc1.WaitProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitProcess not implemented")
}
func (UnimplementedSandboxAgentServer) UpdateContainer(context.Context, *UpdateContainerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContainer not implemented")
}
func (UnimplementedSandboxAgentServer) UpdateEphemeralMounts(context.Context, *UpdateEphemeralMountsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEphemeralMounts not implemented")
}
func (UnimplementedSandboxAgentServer) StatsContainer(context.Context, *StatsContainerRequest) (*grpc1.StatsContainerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StatsContainer not implemented")
}
func (UnimplementedSandboxAgentServer) PauseContainer(context.Context, *PauseContainerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseContainer not implemented")
}
func (UnimplementedSandboxAgentServer) ResumeContainer(context.Context, *ResumeContainerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeContainer not implemented")
}
func (UnimplementedSandboxAgentServer) WriteStdin(context.Context, *WriteStdinRequest) (*grpc1.WriteStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteStdin not implemented")
}
func (UnimplementedSandboxAgentServer) ReadStdout(context.Context, *ReadStdoutRequest) (*grpc1.ReadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadStdout not implemented")
}
func (UnimplementedSandboxAgentServer) ReadStderr(context.Context, *ReadStderrRequest) (*grpc1.ReadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadStderr not implemented")
}
func (UnimplementedSandboxAgentServer) CloseStdin(context.Context, *CloseStdinRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseStdin not implemented")
}
func (UnimplementedSandboxAgentServer) TtyWinResize(context.Context, *TtyWinResizeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TtyWinResize not implemented")
}
func (UnimplementedSandboxAgentServer) UpdateInterface(context.Context, *UpdateInterfaceRequest) (*protocols.Interface, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInterface not implemented")
}
func (UnimplementedSandboxAgentServer) UpdateRoutes(context.Context, *UpdateRoutesRequest) (*grpc1.Routes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoutes not implemented")
}
func (UnimplementedSandboxAgentServer) ListInterfaces(context.Context, *ListInterfacesRequest) (*grpc1.Interfaces, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedSandboxAgentServer) ListRoutes(context.Context, *ListRoutesRequest) (*grpc1.Routes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedSandboxAgentServer) AddARPNeighbors(context.Context, *AddARPNeighborsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddARPNeighbors not implemented")
}
func (UnimplementedSandboxAgentServer) GetIPTables(context.Context, *GetIPTablesRequest) (*grpc1.GetIPTablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIPTables not implemented")
}
func (UnimplementedSandboxAgentServer) SetIPTables(context.Context, *SetIPTablesRequest) (*grpc1.SetIPTablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetIPTables not implemented")
}
func (UnimplementedSandboxAgentServer) GetMetrics(context.Context, *GetMetricsRequest) (*grpc1.Metrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedSandboxAgentServer) MemAgentMemcgSet(context.Context, *MemAgentMemcgSetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MemAgentMemcgSet not implemented")
}
func (UnimplementedSandboxAgentServer) MemAgentCompactSet(context.Context, *MemAgentCompactSetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MemAgentCompactSet not implemented")
}
func (UnimplementedSandboxAgentServer) SetGuestDateTime(context.Context, *SetGuestDateTimeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGuestDateTime not implemented")
}
func (UnimplementedSandboxAgentServer) CopyFile(context.Context, *CopyFileRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedSandboxAgentServer) GetVolumeStats(context.Context, *GetVolumeStatsRequest) (*grpc1.VolumeStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolumeStats not implemented")
}
func (UnimplementedSandboxAgentServer) ResizeVolume(context.Context, *ResizeVolumeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeVolume not implemented")
}
func (UnimplementedSandboxAgentServer) mustEmbedUnimplementedSandboxAgentServer() {}
func (UnimplementedSandboxAgentServer) testEmbeddedByValue()                      {}

// UnsafeSandboxAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxAgentServer will
// result in compilation errors.
type UnsafeSandboxAgentServer interface {
	mustEmbedUnimplementedSandboxAgentServer()
}

func RegisterSandboxAgentServer(s grpc.ServiceRegistrar, srv SandboxAgentServer) {
	// If the following call panics, it indicates UnimplementedSandboxAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxAgent_ServiceDesc, srv)
}

func _SandboxAgent_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_SaveVMState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveVMStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SaveVMState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SaveVMState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SaveVMState(ctx, req.(*SaveVMStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_RestoreVMState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreVMStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).RestoreVMState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_RestoreVMState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).RestoreVMState(ctx, req.(*RestoreVMStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_CreateContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_StartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).StartContainer(ctx, req.(*StartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_RemoveContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).RemoveContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_RemoveContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).RemoveContainer(ctx, req.(*RemoveContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ExecProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ExecProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ExecProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ExecProcess(ctx, req.(*ExecProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_SignalProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SignalProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SignalProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SignalProcess(ctx, req.(*SignalProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_WaitProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).WaitProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_WaitProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).WaitProcess(ctx, req.(*WaitProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_UpdateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).UpdateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_UpdateContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).UpdateContainer(ctx, req.(*UpdateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_UpdateEphemeralMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEphemeralMountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).UpdateEphemeralMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_UpdateEphemeralMounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).UpdateEphemeralMounts(ctx, req.(*UpdateEphemeralMountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_StatsContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).StatsContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_StatsContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).StatsContainer(ctx, req.(*StatsContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_PauseContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).PauseContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_PauseContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).PauseContainer(ctx, req.(*PauseContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ResumeContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ResumeContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ResumeContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ResumeContainer(ctx, req.(*ResumeContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_WriteStdin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteStdinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).WriteStdin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_WriteStdin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).WriteStdin(ctx, req.(*WriteStdinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ReadStdout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStdoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ReadStdout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ReadStdout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ReadStdout(ctx, req.(*ReadStdoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ReadStderr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStderrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ReadStderr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ReadStderr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ReadStderr(ctx, req.(*ReadStderrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_CloseStdin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseStdinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).CloseStdin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_CloseStdin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).CloseStdin(ctx, req.(*CloseStdinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_TtyWinResize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TtyWinResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).TtyWinResize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_TtyWinResize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).TtyWinResize(ctx, req.(*TtyWinResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_UpdateInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).UpdateInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_UpdateInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).UpdateInterface(ctx, req.(*UpdateInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_UpdateRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).UpdateRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_UpdateRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).UpdateRoutes(ctx, req.(*UpdateRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ListInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ListInterfaces(ctx, req.(*ListInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_AddARPNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddARPNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).AddARPNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_AddARPNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).AddARPNeighbors(ctx, req.(*AddARPNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_GetIPTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).GetIPTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_GetIPTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).GetIPTables(ctx, req.(*GetIPTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_SetIPTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetIPTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SetIPTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SetIPTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SetIPTables(ctx, req.(*SetIPTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_MemAgentMemcgSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemAgentMemcgSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).MemAgentMemcgSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_MemAgentMemcgSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).MemAgentMemcgSet(ctx, req.(*MemAgentMemcgSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_MemAgentCompactSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemAgentCompactSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).MemAgentCompactSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_MemAgentCompactSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).MemAgentCompactSet(ctx, req.(*MemAgentCompactSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_SetGuestDateTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGuestDateTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SetGuestDateTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SetGuestDateTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SetGuestDateTime(ctx, req.(*SetGuestDateTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_CopyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).CopyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_CopyFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).CopyFile(ctx, req.(*CopyFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_GetVolumeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).GetVolumeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_GetVolumeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).GetVolumeStats(ctx, req.(*GetVolumeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ResizeVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ResizeVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ResizeVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ResizeVolume(ctx, req.(*ResizeVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxAgent_ServiceDesc is the grpc.ServiceDesc for SandboxAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.v1.SandboxAgent",
	HandlerType: (*SandboxAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _SandboxAgent_Health_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _SandboxAgent_ListVMs_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _SandboxAgent_Exec_Handler,
		},
		{
			MethodName: "SaveVMState",
			Handler:    _SandboxAgent_SaveVMState_Handler,
		},
		{
			MethodName: "RestoreVMState",
			Handler:    _SandboxAgent_RestoreVMState_Handler,
		},
		{
			MethodName: "CreateContainer",
			Handler:    _SandboxAgent_CreateContainer_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _SandboxAgent_StartContainer_Handler,
		},
		{
			MethodName: "RemoveContainer",
			Handler:    _SandboxAgent_RemoveContainer_Handler,
		},
		{
			MethodName: "ExecProcess",
			Handler:    _SandboxAgent_ExecProcess_Handler,
		},
		{
			MethodName: "SignalProcess",
			Handler:    _SandboxAgent_SignalProcess_Handler,
		},
		{
			MethodName: "WaitProcess",
			Handler:    _SandboxAgent_WaitProcess_Handler,
		},
		{
			MethodName: "UpdateContainer",
			Handler:    _SandboxAgent_UpdateContainer_Handler,
		},
		{
			MethodName: "UpdateEphemeralMounts",
			Handler:    _SandboxAgent_UpdateEphemeralMounts_Handler,
		},
		{
			MethodName: "StatsContainer",
			Handler:    _SandboxAgent_StatsContainer_Handler,
		},
		{
			MethodName: "PauseContainer",
			Handler:    _SandboxAgent_PauseContainer_Handler,
		},
		{
			MethodName: "ResumeContainer",
			Handler:    _SandboxAgent_ResumeContainer_Handler,
		},
		{
			MethodName: "WriteStdin",
			Handler:    _SandboxAgent_WriteStdin_Handler,
		},
		{
			MethodName: "ReadStdout",
			Handler:    _SandboxAgent_ReadStdout_Handler,
		},
		{
			MethodName: "ReadStderr",
			Handler:    _SandboxAgent_ReadStderr_Handler,
		},
		{
			MethodName: "CloseStdin",
			Handler:    _SandboxAgent_CloseStdin_Handler,
		},
		{
			MethodName: "TtyWinResize",
			Handler:    _SandboxAgent_TtyWinResize_Handler,
		},
		{
			MethodName: "UpdateInterface",
			Handler:    _SandboxAgent_UpdateInterface_Handler,
		},
		{
			MethodName: "UpdateRoutes",
			Handler:    _SandboxAgent_UpdateRoutes_Handler,
		},
		{
			MethodName: "ListInterfaces",
			Handler:    _SandboxAgent_ListInterfaces_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _SandboxAgent_ListRoutes_Handler,
		},
		{
			MethodName: "AddARPNeighbors",
			Handler:    _SandboxAgent_AddARPNeighbors_Handler,
		},
		{
			MethodName: "GetIPTables",
			Handler:    _SandboxAgent_GetIPTables_Handler,
		},
		{
			MethodName: "SetIPTables",
			Handler:    _SandboxAgent_SetIPTables_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _SandboxAgent_GetMetrics_Handler,
		},
		{
			MethodName: "MemAgentMemcgSet",
			Handler:    _SandboxAgent_MemAgentMemcgSet_Handler,
		},
		{
			MethodName: "MemAgentCompactSet",
			Handler:    _SandboxAgent_MemAgentCompactSet_Handler,
		},
		{
			MethodName: "SetGuestDateTime",
			Handler:    _SandboxAgent_SetGuestDateTime_Handler,
		},
		{
			MethodName: "CopyFile",
			Handler:    _SandboxAgent_CopyFile_Handler,
		},
		{
			MethodName: "GetVolumeStats",
			Handler:    _SandboxAgent_GetVolumeStats_Handler,
		},
		{
			MethodName: "ResizeVolume",
			Handler:    _SandboxAgent_ResizeVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandbox.proto",
}
