// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: sandbox.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // "kata" or "pod"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// Sandbox lifecycle messages
type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSandboxRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateSandboxRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CreateSandboxRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateSandboxRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *GetSandboxRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxRequest) Reset() {
	*x = DeleteSandboxRequest{}
	mi := &file_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxRequest) ProtoMessage() {}

func (x *DeleteSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxRequest.ProtoReflect.Descriptor instead.
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSandboxRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"` // optional filter by node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *ListSandboxesRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*SandboxInfo         `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxInfo {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type UpdateSandboxActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSandboxActivityRequest) Reset() {
	*x = UpdateSandboxActivityRequest{}
	mi := &file_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSandboxActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSandboxActivityRequest) ProtoMessage() {}

func (x *UpdateSandboxActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSandboxActivityRequest.ProtoReflect.Descriptor instead.
func (*UpdateSandboxActivityRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSandboxActivityRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SandboxInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SandboxId      string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Containers     []*ContainerInfo       `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // pending, running, failed, terminated
	Node           string                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	CreatedAtUnix  int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	LastUsedAtUnix int64                  `protobuf:"varint,7,opt,name=last_used_at_unix,json=lastUsedAtUnix,proto3" json:"last_used_at_unix,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *SandboxInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SandboxInfo) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxInfo) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *SandboxInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SandboxInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *SandboxInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *SandboxInfo) GetLastUsedAtUnix() int64 {
	if x != nil {
		return x.LastUsedAtUnix
	}
	return 0
}

func (x *SandboxInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

// Command execution
type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // deprecated, use session_id
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Cwd           string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// Process management
type StartProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Env           []string               `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Tty           bool                   `protobuf:"varint,5,opt,name=tty,proto3" json:"tty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *StartProcessRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartProcessRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartProcessRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartProcessRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartProcessRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

type StartProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *StartProcessResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *StartProcessResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type WriteToProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteToProcessRequest) Reset() {
	*x = WriteToProcessRequest{}
	mi := &file_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteToProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToProcessRequest) ProtoMessage() {}

func (x *WriteToProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToProcessRequest.ProtoReflect.Descriptor instead.
func (*WriteToProcessRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *WriteToProcessRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WriteToProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *WriteToProcessRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadProcessOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	MaxBytes      int32                  `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadProcessOutputRequest) Reset() {
	*x = ReadProcessOutputRequest{}
	mi := &file_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadProcessOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadProcessOutputRequest) ProtoMessage() {}

func (x *ReadProcessOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadProcessOutputRequest.ProtoReflect.Descriptor instead.
func (*ReadProcessOutputRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *ReadProcessOutputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReadProcessOutputRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ReadProcessOutputRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ReadProcessOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadProcessOutputResponse) Reset() {
	*x = ReadProcessOutputResponse{}
	mi := &file_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadProcessOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadProcessOutputResponse) ProtoMessage() {}

func (x *ReadProcessOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadProcessOutputResponse.ProtoReflect.Descriptor instead.
func (*ReadProcessOutputResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *ReadProcessOutputResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CloseProcessStdinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseProcessStdinRequest) Reset() {
	*x = CloseProcessStdinRequest{}
	mi := &file_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseProcessStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseProcessStdinRequest) ProtoMessage() {}

func (x *CloseProcessStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseProcessStdinRequest.ProtoReflect.Descriptor instead.
func (*CloseProcessStdinRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *CloseProcessStdinRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CloseProcessStdinRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type KillProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Signal        int32                  `protobuf:"varint,3,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessRequest) Reset() {
	*x = KillProcessRequest{}
	mi := &file_sandbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessRequest) ProtoMessage() {}

func (x *KillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessRequest.ProtoReflect.Descriptor instead.
func (*KillProcessRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{17}
}

func (x *KillProcessRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KillProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *KillProcessRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type WaitProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitProcessRequest) Reset() {
	*x = WaitProcessRequest{}
	mi := &file_sandbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitProcessRequest) ProtoMessage() {}

func (x *WaitProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitProcessRequest.ProtoReflect.Descriptor instead.
func (*WaitProcessRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{18}
}

func (x *WaitProcessRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WaitProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type WaitProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitProcessResponse) Reset() {
	*x = WaitProcessResponse{}
	mi := &file_sandbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitProcessResponse) ProtoMessage() {}

func (x *WaitProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitProcessResponse.ProtoReflect.Descriptor instead.
func (*WaitProcessResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{19}
}

func (x *WaitProcessResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ResizeTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTerminalRequest) Reset() {
	*x = ResizeTerminalRequest{}
	mi := &file_sandbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTerminalRequest) ProtoMessage() {}

func (x *ResizeTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTerminalRequest.ProtoReflect.Descriptor instead.
func (*ResizeTerminalRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{20}
}

func (x *ResizeTerminalRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResizeTerminalRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ResizeTerminalRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ResizeTerminalRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// File operations
type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_sandbox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{21}
}

func (x *ReadFileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_sandbox_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{22}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"` // file permissions (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_sandbox_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{23}
}

func (x *WriteFileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ReadArchiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // file or directory to archive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArchiveRequest) Reset() {
	*x = ReadArchiveRequest{}
	mi := &file_sandbox_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArchiveRequest) ProtoMessage() {}

func (x *ReadArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArchiveRequest.ProtoReflect.Descriptor instead.
func (*ReadArchiveRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{24}
}

func (x *ReadArchiveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReadArchiveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ArchiveChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // tar data chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveChunk) Reset() {
	*x = ArchiveChunk{}
	mi := &file_sandbox_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveChunk) ProtoMessage() {}

func (x *ArchiveChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveChunk.ProtoReflect.Descriptor instead.
func (*ArchiveChunk) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{25}
}

func (x *ArchiveChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteArchiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*WriteArchiveRequest_Header
	//	*WriteArchiveRequest_Data
	Request       isWriteArchiveRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArchiveRequest) Reset() {
	*x = WriteArchiveRequest{}
	mi := &file_sandbox_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArchiveRequest) ProtoMessage() {}

func (x *WriteArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArchiveRequest.ProtoReflect.Descriptor instead.
func (*WriteArchiveRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{26}
}

func (x *WriteArchiveRequest) GetRequest() isWriteArchiveRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *WriteArchiveRequest) GetHeader() *WriteArchiveHeader {
	if x != nil {
		if x, ok := x.Request.(*WriteArchiveRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *WriteArchiveRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*WriteArchiveRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isWriteArchiveRequest_Request interface {
	isWriteArchiveRequest_Request()
}

type WriteArchiveRequest_Header struct {
	Header *WriteArchiveHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"` // first message: metadata
}

type WriteArchiveRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // subsequent: tar data chunks
}

func (*WriteArchiveRequest_Header) isWriteArchiveRequest_Request() {}

func (*WriteArchiveRequest_Data) isWriteArchiveRequest_Request() {}

type WriteArchiveHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DestDir       string                 `protobuf:"bytes,2,opt,name=dest_dir,json=destDir,proto3" json:"dest_dir,omitempty"` // destination directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArchiveHeader) Reset() {
	*x = WriteArchiveHeader{}
	mi := &file_sandbox_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArchiveHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArchiveHeader) ProtoMessage() {}

func (x *WriteArchiveHeader) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArchiveHeader.ProtoReflect.Descriptor instead.
func (*WriteArchiveHeader) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{27}
}

func (x *WriteArchiveHeader) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WriteArchiveHeader) GetDestDir() string {
	if x != nil {
		return x.DestDir
	}
	return ""
}

type WriteArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArchiveResponse) Reset() {
	*x = WriteArchiveResponse{}
	mi := &file_sandbox_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArchiveResponse) ProtoMessage() {}

func (x *WriteArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArchiveResponse.ProtoReflect.Descriptor instead.
func (*WriteArchiveResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{28}
}

func (x *WriteArchiveResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

// VM state management
type SaveVMStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // deprecated, use session_id
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveVMStateRequest) Reset() {
	*x = SaveVMStateRequest{}
	mi := &file_sandbox_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveVMStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVMStateRequest) ProtoMessage() {}

func (x *SaveVMStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVMStateRequest.ProtoReflect.Descriptor instead.
func (*SaveVMStateRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{29}
}

func (x *SaveVMStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SaveVMStateRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SaveVMStateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RestoreVMStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // deprecated, use session_id
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreVMStateRequest) Reset() {
	*x = RestoreVMStateRequest{}
	mi := &file_sandbox_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreVMStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreVMStateRequest) ProtoMessage() {}

func (x *RestoreVMStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreVMStateRequest.ProtoReflect.Descriptor instead.
func (*RestoreVMStateRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{30}
}

func (x *RestoreVMStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RestoreVMStateRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RestoreVMStateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\n" +
	"sandbox.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"<\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"\xdb\x02\n" +
	"\x14CreateSandboxRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12;\n" +
	"\x03env\x18\x04 \x03(\v2).sandbox.v1.CreateSandboxRequest.EnvEntryR\x03env\x12D\n" +
	"\x06labels\x18\x05 \x03(\v2,.sandbox.v1.CreateSandboxRequest.LabelsEntryR\x06labels\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x11GetSandboxRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"5\n" +
	"\x14DeleteSandboxRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"*\n" +
	"\x14ListSandboxesRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\"N\n" +
	"\x15ListSandboxesResponse\x125\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x17.sandbox.v1.SandboxInfoR\tsandboxes\"=\n" +
	"\x1cUpdateSandboxActivityRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xfd\x02\n" +
	"\vSandboxInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x129\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2\x19.sandbox.v1.ContainerInfoR\n" +
	"containers\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04node\x18\x05 \x01(\tR\x04node\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12)\n" +
	"\x11last_used_at_unix\x18\a \x01(\x03R\x0elastUsedAtUnix\x12;\n" +
	"\x06labels\x18\b \x03(\v2#.sandbox.v1.SandboxInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\rContainerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"\x98\x01\n" +
	"\vExecRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\"[\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"\x84\x01\n" +
	"\x13StartProcessRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x10\n" +
	"\x03tty\x18\x05 \x01(\bR\x03tty\"X\n" +
	"\x14StartProcessResponse\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"i\n" +
	"\x15WriteToProcessRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"u\n" +
	"\x18ReadProcessOutputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\x05R\bmaxBytes\"/\n" +
	"\x19ReadProcessOutputResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"X\n" +
	"\x18CloseProcessStdinRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\"j\n" +
	"\x12KillProcessRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\x05R\x06signal\"R\n" +
	"\x12WaitProcessRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\"2\n" +
	"\x13WaitProcessResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"}\n" +
	"\x15ResizeTerminalRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\rR\x04cols\"D\n" +
	"\x0fReadFileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"s\n" +
	"\x10WriteFileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"G\n" +
	"\x12ReadArchiveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\"\n" +
	"\fArchiveChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"p\n" +
	"\x13WriteArchiveRequest\x128\n" +
	"\x06header\x18\x01 \x01(\v2\x1e.sandbox.v1.WriteArchiveHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\arequest\"N\n" +
	"\x12WriteArchiveHeader\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bdest_dir\x18\x02 \x01(\tR\adestDir\";\n" +
	"\x14WriteArchiveResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"\\\n" +
	"\x12SaveVMStateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"_\n" +
	"\x15RestoreVMStateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path2\xb5\x11\n" +
	"\fSandboxAgent\x12N\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x1a.sandbox.v1.HealthResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthz\x12d\n" +
	"\rCreateSandbox\x12 .sandbox.v1.CreateSandboxRequest\x1a\x17.sandbox.v1.SandboxInfo\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/sandboxes\x12h\n" +
	"\n" +
	"GetSandbox\x12\x1d.sandbox.v1.GetSandboxRequest\x1a\x17.sandbox.v1.SandboxInfo\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/sandboxes/{session_id}\x12m\n" +
	"\rDeleteSandbox\x12 .sandbox.v1.DeleteSandboxRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/sandboxes/{session_id}\x12k\n" +
	"\rListSandboxes\x12 .sandbox.v1.ListSandboxesRequest\x1a!.sandbox.v1.ListSandboxesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/sandboxes\x12\x86\x01\n" +
	"\x15UpdateSandboxActivity\x12(.sandbox.v1.UpdateSandboxActivityRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%\"#/v1/sandboxes/{session_id}/activity\x12N\n" +
	"\x04Exec\x12\x17.sandbox.v1.ExecRequest\x1a\x18.sandbox.v1.ExecResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/exec\x12o\n" +
	"\fStartProcess\x12\x1f.sandbox.v1.StartProcessRequest\x1a .sandbox.v1.StartProcessResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/process/start\x12i\n" +
	"\x0eWriteToProcess\x12!.sandbox.v1.WriteToProcessRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/process/write\x12\x84\x01\n" +
	"\x11ReadProcessStdout\x12$.sandbox.v1.ReadProcessOutputRequest\x1a%.sandbox.v1.ReadProcessOutputResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/process/read/stdout\x12\x84\x01\n" +
	"\x11ReadProcessStderr\x12$.sandbox.v1.ReadProcessOutputRequest\x1a%.sandbox.v1.ReadProcessOutputResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/process/read/stderr\x12u\n" +
	"\x11CloseProcessStdin\x12$.sandbox.v1.CloseProcessStdinRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/process/close-stdin\x12b\n" +
	"\vKillProcess\x12\x1e.sandbox.v1.KillProcessRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/process/kill\x12k\n" +
	"\vWaitProcess\x12\x1e.sandbox.v1.WaitProcessRequest\x1a\x1f.sandbox.v1.WaitProcessResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/process/wait\x12j\n" +
	"\x0eResizeTerminal\x12!.sandbox.v1.ResizeTerminalRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/process/resize\x12`\n" +
	"\bReadFile\x12\x1b.sandbox.v1.ReadFileRequest\x1a\x1c.sandbox.v1.ReadFileResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/files/read\x12]\n" +
	"\tWriteFile\x12\x1c.sandbox.v1.WriteFileRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/files/write\x12I\n" +
	"\vReadArchive\x12\x1e.sandbox.v1.ReadArchiveRequest\x1a\x18.sandbox.v1.ArchiveChunk0\x01\x12S\n" +
	"\fWriteArchive\x12\x1f.sandbox.v1.WriteArchiveRequest\x1a .sandbox.v1.WriteArchiveResponse(\x01\x12c\n" +
	"\vSaveVMState\x12\x1e.sandbox.v1.SaveVMStateRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/vm/save-state\x12l\n" +
	"\x0eRestoreVMState\x12!.sandbox.v1.RestoreVMStateRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/vm/restore-stateBFZDgithub.com/cohere-ai/kata-containers/src/sandbox-agent/pkg/api/pb;pbb\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_sandbox_proto_goTypes = []any{
	(*HealthResponse)(nil),               // 0: sandbox.v1.HealthResponse
	(*CreateSandboxRequest)(nil),         // 1: sandbox.v1.CreateSandboxRequest
	(*GetSandboxRequest)(nil),            // 2: sandbox.v1.GetSandboxRequest
	(*DeleteSandboxRequest)(nil),         // 3: sandbox.v1.DeleteSandboxRequest
	(*ListSandboxesRequest)(nil),         // 4: sandbox.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),        // 5: sandbox.v1.ListSandboxesResponse
	(*UpdateSandboxActivityRequest)(nil), // 6: sandbox.v1.UpdateSandboxActivityRequest
	(*SandboxInfo)(nil),                  // 7: sandbox.v1.SandboxInfo
	(*ContainerInfo)(nil),                // 8: sandbox.v1.ContainerInfo
	(*ExecRequest)(nil),                  // 9: sandbox.v1.ExecRequest
	(*ExecResponse)(nil),                 // 10: sandbox.v1.ExecResponse
	(*StartProcessRequest)(nil),          // 11: sandbox.v1.StartProcessRequest
	(*StartProcessResponse)(nil),         // 12: sandbox.v1.StartProcessResponse
	(*WriteToProcessRequest)(nil),        // 13: sandbox.v1.WriteToProcessRequest
	(*ReadProcessOutputRequest)(nil),     // 14: sandbox.v1.ReadProcessOutputRequest
	(*ReadProcessOutputResponse)(nil),    // 15: sandbox.v1.ReadProcessOutputResponse
	(*CloseProcessStdinRequest)(nil),     // 16: sandbox.v1.CloseProcessStdinRequest
	(*KillProcessRequest)(nil),           // 17: sandbox.v1.KillProcessRequest
	(*WaitProcessRequest)(nil),           // 18: sandbox.v1.WaitProcessRequest
	(*WaitProcessResponse)(nil),          // 19: sandbox.v1.WaitProcessResponse
	(*ResizeTerminalRequest)(nil),        // 20: sandbox.v1.ResizeTerminalRequest
	(*ReadFileRequest)(nil),              // 21: sandbox.v1.ReadFileRequest
	(*ReadFileResponse)(nil),             // 22: sandbox.v1.ReadFileResponse
	(*WriteFileRequest)(nil),             // 23: sandbox.v1.WriteFileRequest
	(*ReadArchiveRequest)(nil),           // 24: sandbox.v1.ReadArchiveRequest
	(*ArchiveChunk)(nil),                 // 25: sandbox.v1.ArchiveChunk
	(*WriteArchiveRequest)(nil),          // 26: sandbox.v1.WriteArchiveRequest
	(*WriteArchiveHeader)(nil),           // 27: sandbox.v1.WriteArchiveHeader
	(*WriteArchiveResponse)(nil),         // 28: sandbox.v1.WriteArchiveResponse
	(*SaveVMStateRequest)(nil),           // 29: sandbox.v1.SaveVMStateRequest
	(*RestoreVMStateRequest)(nil),        // 30: sandbox.v1.RestoreVMStateRequest
	nil,                                  // 31: sandbox.v1.CreateSandboxRequest.EnvEntry
	nil,                                  // 32: sandbox.v1.CreateSandboxRequest.LabelsEntry
	nil,                                  // 33: sandbox.v1.SandboxInfo.LabelsEntry
	(*emptypb.Empty)(nil),                // 34: google.protobuf.Empty
}
var file_sandbox_proto_depIdxs = []int32{
	31, // 0: sandbox.v1.CreateSandboxRequest.env:type_name -> sandbox.v1.CreateSandboxRequest.EnvEntry
	32, // 1: sandbox.v1.CreateSandboxRequest.labels:type_name -> sandbox.v1.CreateSandboxRequest.LabelsEntry
	7,  // 2: sandbox.v1.ListSandboxesResponse.sandboxes:type_name -> sandbox.v1.SandboxInfo
	8,  // 3: sandbox.v1.SandboxInfo.containers:type_name -> sandbox.v1.ContainerInfo
	33, // 4: sandbox.v1.SandboxInfo.labels:type_name -> sandbox.v1.SandboxInfo.LabelsEntry
	27, // 5: sandbox.v1.WriteArchiveRequest.header:type_name -> sandbox.v1.WriteArchiveHeader
	34, // 6: sandbox.v1.SandboxAgent.Health:input_type -> google.protobuf.Empty
	1,  // 7: sandbox.v1.SandboxAgent.CreateSandbox:input_type -> sandbox.v1.CreateSandboxRequest
	2,  // 8: sandbox.v1.SandboxAgent.GetSandbox:input_type -> sandbox.v1.GetSandboxRequest
	3,  // 9: sandbox.v1.SandboxAgent.DeleteSandbox:input_type -> sandbox.v1.DeleteSandboxRequest
	4,  // 10: sandbox.v1.SandboxAgent.ListSandboxes:input_type -> sandbox.v1.ListSandboxesRequest
	6,  // 11: sandbox.v1.SandboxAgent.UpdateSandboxActivity:input_type -> sandbox.v1.UpdateSandboxActivityRequest
	9,  // 12: sandbox.v1.SandboxAgent.Exec:input_type -> sandbox.v1.ExecRequest
	11, // 13: sandbox.v1.SandboxAgent.StartProcess:input_type -> sandbox.v1.StartProcessRequest
	13, // 14: sandbox.v1.SandboxAgent.WriteToProcess:input_type -> sandbox.v1.WriteToProcessRequest
	14, // 15: sandbox.v1.SandboxAgent.ReadProcessStdout:input_type -> sandbox.v1.ReadProcessOutputRequest
	14, // 16: sandbox.v1.SandboxAgent.ReadProcessStderr:input_type -> sandbox.v1.ReadProcessOutputRequest
	16, // 17: sandbox.v1.SandboxAgent.CloseProcessStdin:input_type -> sandbox.v1.CloseProcessStdinRequest
	17, // 18: sandbox.v1.SandboxAgent.KillProcess:input_type -> sandbox.v1.KillProcessRequest
	18, // 19: sandbox.v1.SandboxAgent.WaitProcess:input_type -> sandbox.v1.WaitProcessRequest
	20, // 20: sandbox.v1.SandboxAgent.ResizeTerminal:input_type -> sandbox.v1.ResizeTerminalRequest
	21, // 21: sandbox.v1.SandboxAgent.ReadFile:input_type -> sandbox.v1.ReadFileRequest
	23, // 22: sandbox.v1.SandboxAgent.WriteFile:input_type -> sandbox.v1.WriteFileRequest
	24, // 23: sandbox.v1.SandboxAgent.ReadArchive:input_type -> sandbox.v1.ReadArchiveRequest
	26, // 24: sandbox.v1.SandboxAgent.WriteArchive:input_type -> sandbox.v1.WriteArchiveRequest
	29, // 25: sandbox.v1.SandboxAgent.SaveVMState:input_type -> sandbox.v1.SaveVMStateRequest
	30, // 26: sandbox.v1.SandboxAgent.RestoreVMState:input_type -> sandbox.v1.RestoreVMStateRequest
	0,  // 27: sandbox.v1.SandboxAgent.Health:output_type -> sandbox.v1.HealthResponse
	7,  // 28: sandbox.v1.SandboxAgent.CreateSandbox:output_type -> sandbox.v1.SandboxInfo
	7,  // 29: sandbox.v1.SandboxAgent.GetSandbox:output_type -> sandbox.v1.SandboxInfo
	34, // 30: sandbox.v1.SandboxAgent.DeleteSandbox:output_type -> google.protobuf.Empty
	5,  // 31: sandbox.v1.SandboxAgent.ListSandboxes:output_type -> sandbox.v1.ListSandboxesResponse
	34, // 32: sandbox.v1.SandboxAgent.UpdateSandboxActivity:output_type -> google.protobuf.Empty
	10, // 33: sandbox.v1.SandboxAgent.Exec:output_type -> sandbox.v1.ExecResponse
	12, // 34: sandbox.v1.SandboxAgent.StartProcess:output_type -> sandbox.v1.StartProcessResponse
	34, // 35: sandbox.v1.SandboxAgent.WriteToProcess:output_type -> google.protobuf.Empty
	15, // 36: sandbox.v1.SandboxAgent.ReadProcessStdout:output_type -> sandbox.v1.ReadProcessOutputResponse
	15, // 37: sandbox.v1.SandboxAgent.ReadProcessStderr:output_type -> sandbox.v1.ReadProcessOutputResponse
	34, // 38: sandbox.v1.SandboxAgent.CloseProcessStdin:output_type -> google.protobuf.Empty
	34, // 39: sandbox.v1.SandboxAgent.KillProcess:output_type -> google.protobuf.Empty
	19, // 40: sandbox.v1.SandboxAgent.WaitProcess:output_type -> sandbox.v1.WaitProcessResponse
	34, // 41: sandbox.v1.SandboxAgent.ResizeTerminal:output_type -> google.protobuf.Empty
	22, // 42: sandbox.v1.SandboxAgent.ReadFile:output_type -> sandbox.v1.ReadFileResponse
	34, // 43: sandbox.v1.SandboxAgent.WriteFile:output_type -> google.protobuf.Empty
	25, // 44: sandbox.v1.SandboxAgent.ReadArchive:output_type -> sandbox.v1.ArchiveChunk
	28, // 45: sandbox.v1.SandboxAgent.WriteArchive:output_type -> sandbox.v1.WriteArchiveResponse
	34, // 46: sandbox.v1.SandboxAgent.SaveVMState:output_type -> google.protobuf.Empty
	34, // 47: sandbox.v1.SandboxAgent.RestoreVMState:output_type -> google.protobuf.Empty
	27, // [27:48] is the sub-list for method output_type
	6,  // [6:27] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	file_sandbox_proto_msgTypes[26].OneofWrappers = []any{
		(*WriteArchiveRequest_Header)(nil),
		(*WriteArchiveRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
