// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: sandbox.proto

package pb

import (
	protocols "github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols"
	grpc "github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols/grpc"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ListVMsRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMInfo              `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *ListVMsResponse) GetVms() []*VMInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

type VMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMInfo) Reset() {
	*x = VMInfo{}
	mi := &file_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMInfo) ProtoMessage() {}

func (x *VMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMInfo.ProtoReflect.Descriptor instead.
func (*VMInfo) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *VMInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type SaveVMStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveVMStateRequest) Reset() {
	*x = SaveVMStateRequest{}
	mi := &file_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveVMStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVMStateRequest) ProtoMessage() {}

func (x *SaveVMStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVMStateRequest.ProtoReflect.Descriptor instead.
func (*SaveVMStateRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *SaveVMStateRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SaveVMStateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RestoreVMStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreVMStateRequest) Reset() {
	*x = RestoreVMStateRequest{}
	mi := &file_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreVMStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreVMStateRequest) ProtoMessage() {}

func (x *RestoreVMStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreVMStateRequest.ProtoReflect.Descriptor instead.
func (*RestoreVMStateRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreVMStateRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RestoreVMStateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Cwd           string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *ExecRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ExecRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type CreateContainerRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	VmId          string                       `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.CreateContainerRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *CreateContainerRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateContainerRequest) GetRequest() *grpc.CreateContainerRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type StartContainerRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	VmId          string                      `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.StartContainerRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerRequest) Reset() {
	*x = StartContainerRequest{}
	mi := &file_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerRequest) ProtoMessage() {}

func (x *StartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerRequest.ProtoReflect.Descriptor instead.
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *StartContainerRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StartContainerRequest) GetRequest() *grpc.StartContainerRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type RemoveContainerRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	VmId          string                       `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.RemoveContainerRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerRequest) Reset() {
	*x = RemoveContainerRequest{}
	mi := &file_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerRequest) ProtoMessage() {}

func (x *RemoveContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerRequest.ProtoReflect.Descriptor instead.
func (*RemoveContainerRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveContainerRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RemoveContainerRequest) GetRequest() *grpc.RemoveContainerRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ExecProcessRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	VmId          string                   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.ExecProcessRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecProcessRequest) Reset() {
	*x = ExecProcessRequest{}
	mi := &file_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecProcessRequest) ProtoMessage() {}

func (x *ExecProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecProcessRequest.ProtoReflect.Descriptor instead.
func (*ExecProcessRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *ExecProcessRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ExecProcessRequest) GetRequest() *grpc.ExecProcessRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type SignalProcessRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	VmId          string                     `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.SignalProcessRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalProcessRequest) Reset() {
	*x = SignalProcessRequest{}
	mi := &file_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalProcessRequest) ProtoMessage() {}

func (x *SignalProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalProcessRequest.ProtoReflect.Descriptor instead.
func (*SignalProcessRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *SignalProcessRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SignalProcessRequest) GetRequest() *grpc.SignalProcessRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type WaitProcessRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	VmId          string                   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.WaitProcessRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitProcessRequest) Reset() {
	*x = WaitProcessRequest{}
	mi := &file_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitProcessRequest) ProtoMessage() {}

func (x *WaitProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitProcessRequest.ProtoReflect.Descriptor instead.
func (*WaitProcessRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *WaitProcessRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *WaitProcessRequest) GetRequest() *grpc.WaitProcessRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateContainerRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	VmId          string                       `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.UpdateContainerRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContainerRequest) Reset() {
	*x = UpdateContainerRequest{}
	mi := &file_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContainerRequest) ProtoMessage() {}

func (x *UpdateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContainerRequest.ProtoReflect.Descriptor instead.
func (*UpdateContainerRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateContainerRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *UpdateContainerRequest) GetRequest() *grpc.UpdateContainerRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateEphemeralMountsRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	VmId          string                             `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.UpdateEphemeralMountsRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEphemeralMountsRequest) Reset() {
	*x = UpdateEphemeralMountsRequest{}
	mi := &file_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEphemeralMountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEphemeralMountsRequest) ProtoMessage() {}

func (x *UpdateEphemeralMountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEphemeralMountsRequest.ProtoReflect.Descriptor instead.
func (*UpdateEphemeralMountsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateEphemeralMountsRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *UpdateEphemeralMountsRequest) GetRequest() *grpc.UpdateEphemeralMountsRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type StatsContainerRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	VmId          string                      `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.StatsContainerRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsContainerRequest) Reset() {
	*x = StatsContainerRequest{}
	mi := &file_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsContainerRequest) ProtoMessage() {}

func (x *StatsContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsContainerRequest.ProtoReflect.Descriptor instead.
func (*StatsContainerRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *StatsContainerRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StatsContainerRequest) GetRequest() *grpc.StatsContainerRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type PauseContainerRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	VmId          string                      `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.PauseContainerRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseContainerRequest) Reset() {
	*x = PauseContainerRequest{}
	mi := &file_sandbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseContainerRequest) ProtoMessage() {}

func (x *PauseContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseContainerRequest.ProtoReflect.Descriptor instead.
func (*PauseContainerRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{17}
}

func (x *PauseContainerRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *PauseContainerRequest) GetRequest() *grpc.PauseContainerRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ResumeContainerRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	VmId          string                       `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.ResumeContainerRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeContainerRequest) Reset() {
	*x = ResumeContainerRequest{}
	mi := &file_sandbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeContainerRequest) ProtoMessage() {}

func (x *ResumeContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeContainerRequest.ProtoReflect.Descriptor instead.
func (*ResumeContainerRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{18}
}

func (x *ResumeContainerRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ResumeContainerRequest) GetRequest() *grpc.ResumeContainerRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type WriteStdinRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	VmId          string                   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.WriteStreamRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinRequest) Reset() {
	*x = WriteStdinRequest{}
	mi := &file_sandbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinRequest) ProtoMessage() {}

func (x *WriteStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinRequest.ProtoReflect.Descriptor instead.
func (*WriteStdinRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{19}
}

func (x *WriteStdinRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *WriteStdinRequest) GetRequest() *grpc.WriteStreamRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ReadStdoutRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	VmId          string                  `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.ReadStreamRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStdoutRequest) Reset() {
	*x = ReadStdoutRequest{}
	mi := &file_sandbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStdoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStdoutRequest) ProtoMessage() {}

func (x *ReadStdoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStdoutRequest.ProtoReflect.Descriptor instead.
func (*ReadStdoutRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{20}
}

func (x *ReadStdoutRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ReadStdoutRequest) GetRequest() *grpc.ReadStreamRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ReadStderrRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	VmId          string                  `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.ReadStreamRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStderrRequest) Reset() {
	*x = ReadStderrRequest{}
	mi := &file_sandbox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStderrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStderrRequest) ProtoMessage() {}

func (x *ReadStderrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStderrRequest.ProtoReflect.Descriptor instead.
func (*ReadStderrRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{21}
}

func (x *ReadStderrRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ReadStderrRequest) GetRequest() *grpc.ReadStreamRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type CloseStdinRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	VmId          string                  `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.CloseStdinRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStdinRequest) Reset() {
	*x = CloseStdinRequest{}
	mi := &file_sandbox_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStdinRequest) ProtoMessage() {}

func (x *CloseStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStdinRequest.ProtoReflect.Descriptor instead.
func (*CloseStdinRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{22}
}

func (x *CloseStdinRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CloseStdinRequest) GetRequest() *grpc.CloseStdinRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type TtyWinResizeRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	VmId          string                    `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.TtyWinResizeRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtyWinResizeRequest) Reset() {
	*x = TtyWinResizeRequest{}
	mi := &file_sandbox_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtyWinResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtyWinResizeRequest) ProtoMessage() {}

func (x *TtyWinResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtyWinResizeRequest.ProtoReflect.Descriptor instead.
func (*TtyWinResizeRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{23}
}

func (x *TtyWinResizeRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *TtyWinResizeRequest) GetRequest() *grpc.TtyWinResizeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateInterfaceRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	VmId          string                       `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.UpdateInterfaceRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInterfaceRequest) Reset() {
	*x = UpdateInterfaceRequest{}
	mi := &file_sandbox_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInterfaceRequest) ProtoMessage() {}

func (x *UpdateInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInterfaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateInterfaceRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *UpdateInterfaceRequest) GetRequest() *grpc.UpdateInterfaceRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateRoutesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	VmId          string                    `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.UpdateRoutesRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoutesRequest) Reset() {
	*x = UpdateRoutesRequest{}
	mi := &file_sandbox_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutesRequest) ProtoMessage() {}

func (x *UpdateRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutesRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoutesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateRoutesRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *UpdateRoutesRequest) GetRequest() *grpc.UpdateRoutesRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ListInterfacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesRequest) Reset() {
	*x = ListInterfacesRequest{}
	mi := &file_sandbox_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesRequest) ProtoMessage() {}

func (x *ListInterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesRequest.ProtoReflect.Descriptor instead.
func (*ListInterfacesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{26}
}

func (x *ListInterfacesRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_sandbox_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{27}
}

func (x *ListRoutesRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type AddARPNeighborsRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	VmId          string                       `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.AddARPNeighborsRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddARPNeighborsRequest) Reset() {
	*x = AddARPNeighborsRequest{}
	mi := &file_sandbox_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddARPNeighborsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddARPNeighborsRequest) ProtoMessage() {}

func (x *AddARPNeighborsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddARPNeighborsRequest.ProtoReflect.Descriptor instead.
func (*AddARPNeighborsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{28}
}

func (x *AddARPNeighborsRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *AddARPNeighborsRequest) GetRequest() *grpc.AddARPNeighborsRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetIPTablesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	VmId          string                   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.GetIPTablesRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPTablesRequest) Reset() {
	*x = GetIPTablesRequest{}
	mi := &file_sandbox_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPTablesRequest) ProtoMessage() {}

func (x *GetIPTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPTablesRequest.ProtoReflect.Descriptor instead.
func (*GetIPTablesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{29}
}

func (x *GetIPTablesRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetIPTablesRequest) GetRequest() *grpc.GetIPTablesRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type SetIPTablesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	VmId          string                   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.SetIPTablesRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetIPTablesRequest) Reset() {
	*x = SetIPTablesRequest{}
	mi := &file_sandbox_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIPTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIPTablesRequest) ProtoMessage() {}

func (x *SetIPTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIPTablesRequest.ProtoReflect.Descriptor instead.
func (*SetIPTablesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{30}
}

func (x *SetIPTablesRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SetIPTablesRequest) GetRequest() *grpc.SetIPTablesRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_sandbox_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{31}
}

func (x *GetMetricsRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type MemAgentMemcgSetRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	VmId          string                    `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.MemAgentMemcgConfig `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemAgentMemcgSetRequest) Reset() {
	*x = MemAgentMemcgSetRequest{}
	mi := &file_sandbox_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemAgentMemcgSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemAgentMemcgSetRequest) ProtoMessage() {}

func (x *MemAgentMemcgSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemAgentMemcgSetRequest.ProtoReflect.Descriptor instead.
func (*MemAgentMemcgSetRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{32}
}

func (x *MemAgentMemcgSetRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *MemAgentMemcgSetRequest) GetRequest() *grpc.MemAgentMemcgConfig {
	if x != nil {
		return x.Request
	}
	return nil
}

type MemAgentCompactSetRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	VmId          string                      `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.MemAgentCompactConfig `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemAgentCompactSetRequest) Reset() {
	*x = MemAgentCompactSetRequest{}
	mi := &file_sandbox_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemAgentCompactSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemAgentCompactSetRequest) ProtoMessage() {}

func (x *MemAgentCompactSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemAgentCompactSetRequest.ProtoReflect.Descriptor instead.
func (*MemAgentCompactSetRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{33}
}

func (x *MemAgentCompactSetRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *MemAgentCompactSetRequest) GetRequest() *grpc.MemAgentCompactConfig {
	if x != nil {
		return x.Request
	}
	return nil
}

type SetGuestDateTimeRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	VmId          string                        `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.SetGuestDateTimeRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGuestDateTimeRequest) Reset() {
	*x = SetGuestDateTimeRequest{}
	mi := &file_sandbox_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGuestDateTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGuestDateTimeRequest) ProtoMessage() {}

func (x *SetGuestDateTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGuestDateTimeRequest.ProtoReflect.Descriptor instead.
func (*SetGuestDateTimeRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{34}
}

func (x *SetGuestDateTimeRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *SetGuestDateTimeRequest) GetRequest() *grpc.SetGuestDateTimeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type CopyFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.CopyFileRequest  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileRequest) Reset() {
	*x = CopyFileRequest{}
	mi := &file_sandbox_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileRequest) ProtoMessage() {}

func (x *CopyFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileRequest.ProtoReflect.Descriptor instead.
func (*CopyFileRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{35}
}

func (x *CopyFileRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CopyFileRequest) GetRequest() *grpc.CopyFileRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetVolumeStatsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	VmId          string                   `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.VolumeStatsRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeStatsRequest) Reset() {
	*x = GetVolumeStatsRequest{}
	mi := &file_sandbox_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeStatsRequest) ProtoMessage() {}

func (x *GetVolumeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeStatsRequest.ProtoReflect.Descriptor instead.
func (*GetVolumeStatsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{36}
}

func (x *GetVolumeStatsRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetVolumeStatsRequest) GetRequest() *grpc.VolumeStatsRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ResizeVolumeRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	VmId          string                    `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Request       *grpc.ResizeVolumeRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeVolumeRequest) Reset() {
	*x = ResizeVolumeRequest{}
	mi := &file_sandbox_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeVolumeRequest) ProtoMessage() {}

func (x *ResizeVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeVolumeRequest.ProtoReflect.Descriptor instead.
func (*ResizeVolumeRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{37}
}

func (x *ResizeVolumeRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ResizeVolumeRequest) GetRequest() *grpc.ResizeVolumeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\n" +
	"sandbox.v1\x1a\vagent.proto\x1a\tcsi.proto\x1a\vtypes.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"$\n" +
	"\x0eListVMsRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\"7\n" +
	"\x0fListVMsResponse\x12$\n" +
	"\x03vms\x18\x01 \x03(\v2\x12.sandbox.v1.VMInfoR\x03vms\"1\n" +
	"\x06VMInfo\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\"=\n" +
	"\x12SaveVMStateRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"@\n" +
	"\x15RestoreVMStateRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x9c\x01\n" +
	"\vExecRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\"[\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"e\n" +
	"\x16CreateContainerRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1c.grpc.CreateContainerRequestR\arequest\"c\n" +
	"\x15StartContainerRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x125\n" +
	"\arequest\x18\x02 \x01(\v2\x1b.grpc.StartContainerRequestR\arequest\"e\n" +
	"\x16RemoveContainerRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1c.grpc.RemoveContainerRequestR\arequest\"]\n" +
	"\x12ExecProcessRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x122\n" +
	"\arequest\x18\x02 \x01(\v2\x18.grpc.ExecProcessRequestR\arequest\"a\n" +
	"\x14SignalProcessRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x124\n" +
	"\arequest\x18\x02 \x01(\v2\x1a.grpc.SignalProcessRequestR\arequest\"]\n" +
	"\x12WaitProcessRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x122\n" +
	"\arequest\x18\x02 \x01(\v2\x18.grpc.WaitProcessRequestR\arequest\"e\n" +
	"\x16UpdateContainerRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1c.grpc.UpdateContainerRequestR\arequest\"q\n" +
	"\x1cUpdateEphemeralMountsRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12<\n" +
	"\arequest\x18\x02 \x01(\v2\".grpc.UpdateEphemeralMountsRequestR\arequest\"c\n" +
	"\x15StatsContainerRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x125\n" +
	"\arequest\x18\x02 \x01(\v2\x1b.grpc.StatsContainerRequestR\arequest\"c\n" +
	"\x15PauseContainerRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x125\n" +
	"\arequest\x18\x02 \x01(\v2\x1b.grpc.PauseContainerRequestR\arequest\"e\n" +
	"\x16ResumeContainerRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1c.grpc.ResumeContainerRequestR\arequest\"\\\n" +
	"\x11WriteStdinRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x122\n" +
	"\arequest\x18\x02 \x01(\v2\x18.grpc.WriteStreamRequestR\arequest\"[\n" +
	"\x11ReadStdoutRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x121\n" +
	"\arequest\x18\x02 \x01(\v2\x17.grpc.ReadStreamRequestR\arequest\"[\n" +
	"\x11ReadStderrRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x121\n" +
	"\arequest\x18\x02 \x01(\v2\x17.grpc.ReadStreamRequestR\arequest\"[\n" +
	"\x11CloseStdinRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x121\n" +
	"\arequest\x18\x02 \x01(\v2\x17.grpc.CloseStdinRequestR\arequest\"_\n" +
	"\x13TtyWinResizeRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x123\n" +
	"\arequest\x18\x02 \x01(\v2\x19.grpc.TtyWinResizeRequestR\arequest\"e\n" +
	"\x16UpdateInterfaceRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1c.grpc.UpdateInterfaceRequestR\arequest\"_\n" +
	"\x13UpdateRoutesRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x123\n" +
	"\arequest\x18\x02 \x01(\v2\x19.grpc.UpdateRoutesRequestR\arequest\",\n" +
	"\x15ListInterfacesRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"(\n" +
	"\x11ListRoutesRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"e\n" +
	"\x16AddARPNeighborsRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1c.grpc.AddARPNeighborsRequestR\arequest\"]\n" +
	"\x12GetIPTablesRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x122\n" +
	"\arequest\x18\x02 \x01(\v2\x18.grpc.GetIPTablesRequestR\arequest\"]\n" +
	"\x12SetIPTablesRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x122\n" +
	"\arequest\x18\x02 \x01(\v2\x18.grpc.SetIPTablesRequestR\arequest\"(\n" +
	"\x11GetMetricsRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"c\n" +
	"\x17MemAgentMemcgSetRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x123\n" +
	"\arequest\x18\x02 \x01(\v2\x19.grpc.MemAgentMemcgConfigR\arequest\"g\n" +
	"\x19MemAgentCompactSetRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x125\n" +
	"\arequest\x18\x02 \x01(\v2\x1b.grpc.MemAgentCompactConfigR\arequest\"g\n" +
	"\x17SetGuestDateTimeRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x127\n" +
	"\arequest\x18\x02 \x01(\v2\x1d.grpc.SetGuestDateTimeRequestR\arequest\"W\n" +
	"\x0fCopyFileRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12/\n" +
	"\arequest\x18\x02 \x01(\v2\x15.grpc.CopyFileRequestR\arequest\"`\n" +
	"\x15GetVolumeStatsRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x122\n" +
	"\arequest\x18\x02 \x01(\v2\x18.grpc.VolumeStatsRequestR\arequest\"_\n" +
	"\x13ResizeVolumeRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x123\n" +
	"\arequest\x18\x02 \x01(\v2\x19.grpc.ResizeVolumeRequestR\arequest2\xe4\x1d\n" +
	"\fSandboxAgent\x12N\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x1a.sandbox.v1.HealthResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthz\x12T\n" +
	"\aListVMs\x12\x1a.sandbox.v1.ListVMsRequest\x1a\x1b.sandbox.v1.ListVMsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/list\x12N\n" +
	"\x04Exec\x12\x17.sandbox.v1.ExecRequest\x1a\x18.sandbox.v1.ExecResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/exec\x12c\n" +
	"\vSaveVMState\x12\x1e.sandbox.v1.SaveVMStateRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/vm/save-state\x12l\n" +
	"\x0eRestoreVMState\x12!.sandbox.v1.RestoreVMStateRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/vm/restore-state\x12t\n" +
	"\x0fCreateContainer\x12\".sandbox.v1.CreateContainerRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/agent/create-container\x12q\n" +
	"\x0eStartContainer\x12!.sandbox.v1.StartContainerRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/agent/start-container\x12t\n" +
	"\x0fRemoveContainer\x12\".sandbox.v1.RemoveContainerRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/agent/remove-container\x12h\n" +
	"\vExecProcess\x12\x1e.sandbox.v1.ExecProcessRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/agent/exec-process\x12n\n" +
	"\rSignalProcess\x12 .sandbox.v1.SignalProcessRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/agent/signal-process\x12k\n" +
	"\vWaitProcess\x12\x1e.sandbox.v1.WaitProcessRequest\x1a\x19.grpc.WaitProcessResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/agent/wait-process\x12t\n" +
	"\x0fUpdateContainer\x12\".sandbox.v1.UpdateContainerRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/agent/update-container\x12\x87\x01\n" +
	"\x15UpdateEphemeralMounts\x12(.sandbox.v1.UpdateEphemeralMountsRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/agent/update-ephemeral-mounts\x12w\n" +
	"\x0eStatsContainer\x12!.sandbox.v1.StatsContainerRequest\x1a\x1c.grpc.StatsContainerResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/agent/stats-container\x12q\n" +
	"\x0ePauseContainer\x12!.sandbox.v1.PauseContainerRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/agent/pause-container\x12t\n" +
	"\x0fResumeContainer\x12\".sandbox.v1.ResumeContainerRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/agent/resume-container\x12h\n" +
	"\n" +
	"WriteStdin\x12\x1d.sandbox.v1.WriteStdinRequest\x1a\x19.grpc.WriteStreamResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/agent/write-stdin\x12g\n" +
	"\n" +
	"ReadStdout\x12\x1d.sandbox.v1.ReadStdoutRequest\x1a\x18.grpc.ReadStreamResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/agent/read-stdout\x12g\n" +
	"\n" +
	"ReadStderr\x12\x1d.sandbox.v1.ReadStderrRequest\x1a\x18.grpc.ReadStreamResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/agent/read-stderr\x12e\n" +
	"\n" +
	"CloseStdin\x12\x1d.sandbox.v1.CloseStdinRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/agent/close-stdin\x12l\n" +
	"\fTtyWinResize\x12\x1f.sandbox.v1.TtyWinResizeRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/agent/tty-win-resize\x12n\n" +
	"\x0fUpdateInterface\x12\".sandbox.v1.UpdateInterfaceRequest\x1a\x10.types.Interface\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/agent/update-interface\x12a\n" +
	"\fUpdateRoutes\x12\x1f.sandbox.v1.UpdateRoutesRequest\x1a\f.grpc.Routes\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/agent/update-routes\x12k\n" +
	"\x0eListInterfaces\x12!.sandbox.v1.ListInterfacesRequest\x1a\x10.grpc.Interfaces\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/agent/list-interfaces\x12[\n" +
	"\n" +
	"ListRoutes\x12\x1d.sandbox.v1.ListRoutesRequest\x1a\f.grpc.Routes\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/agent/list-routes\x12u\n" +
	"\x0fAddARPNeighbors\x12\".sandbox.v1.AddARPNeighborsRequest\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/agent/add-arp-neighbors\x12k\n" +
	"\vGetIPTables\x12\x1e.sandbox.v1.GetIPTablesRequest\x1a\x19.grpc.GetIPTablesResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/agent/get-iptables\x12k\n" +
	"\vSetIPTables\x12\x1e.sandbox.v1.SetIPTablesRequest\x1a\x19.grpc.SetIPTablesResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/agent/set-iptables\x12\\\n" +
	"\n" +
	"GetMetrics\x12\x1d.sandbox.v1.GetMetricsRequest\x1a\r.grpc.Metrics\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/agent/get-metrics\x12o\n" +
	"\x10MemAgentMemcgSet\x12#.sandbox.v1.MemAgentMemcgSetRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/agent/memcg-set\x12u\n" +
	"\x12MemAgentCompactSet\x12%.sandbox.v1.MemAgentCompactSetRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/agent/compact-set\x12y\n" +
	"\x10SetGuestDateTime\x12#.sandbox.v1.SetGuestDateTimeRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/agent/set-guest-date-time\x12_\n" +
	"\bCopyFile\x12\x1b.sandbox.v1.CopyFileRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/agent/copy-file\x12u\n" +
	"\x0eGetVolumeStats\x12!.sandbox.v1.GetVolumeStatsRequest\x1a\x19.grpc.VolumeStatsResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/agent/get-volume-stats\x12k\n" +
	"\fResizeVolume\x12\x1f.sandbox.v1.ResizeVolumeRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/agent/resize-volumeBFZDgithub.com/cohere-ai/kata-containers/src/sandbox-agent/pkg/api/pb;pbb\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_sandbox_proto_goTypes = []any{
	(*HealthResponse)(nil),                    // 0: sandbox.v1.HealthResponse
	(*ListVMsRequest)(nil),                    // 1: sandbox.v1.ListVMsRequest
	(*ListVMsResponse)(nil),                   // 2: sandbox.v1.ListVMsResponse
	(*VMInfo)(nil),                            // 3: sandbox.v1.VMInfo
	(*SaveVMStateRequest)(nil),                // 4: sandbox.v1.SaveVMStateRequest
	(*RestoreVMStateRequest)(nil),             // 5: sandbox.v1.RestoreVMStateRequest
	(*ExecRequest)(nil),                       // 6: sandbox.v1.ExecRequest
	(*ExecResponse)(nil),                      // 7: sandbox.v1.ExecResponse
	(*CreateContainerRequest)(nil),            // 8: sandbox.v1.CreateContainerRequest
	(*StartContainerRequest)(nil),             // 9: sandbox.v1.StartContainerRequest
	(*RemoveContainerRequest)(nil),            // 10: sandbox.v1.RemoveContainerRequest
	(*ExecProcessRequest)(nil),                // 11: sandbox.v1.ExecProcessRequest
	(*SignalProcessRequest)(nil),              // 12: sandbox.v1.SignalProcessRequest
	(*WaitProcessRequest)(nil),                // 13: sandbox.v1.WaitProcessRequest
	(*UpdateContainerRequest)(nil),            // 14: sandbox.v1.UpdateContainerRequest
	(*UpdateEphemeralMountsRequest)(nil),      // 15: sandbox.v1.UpdateEphemeralMountsRequest
	(*StatsContainerRequest)(nil),             // 16: sandbox.v1.StatsContainerRequest
	(*PauseContainerRequest)(nil),             // 17: sandbox.v1.PauseContainerRequest
	(*ResumeContainerRequest)(nil),            // 18: sandbox.v1.ResumeContainerRequest
	(*WriteStdinRequest)(nil),                 // 19: sandbox.v1.WriteStdinRequest
	(*ReadStdoutRequest)(nil),                 // 20: sandbox.v1.ReadStdoutRequest
	(*ReadStderrRequest)(nil),                 // 21: sandbox.v1.ReadStderrRequest
	(*CloseStdinRequest)(nil),                 // 22: sandbox.v1.CloseStdinRequest
	(*TtyWinResizeRequest)(nil),               // 23: sandbox.v1.TtyWinResizeRequest
	(*UpdateInterfaceRequest)(nil),            // 24: sandbox.v1.UpdateInterfaceRequest
	(*UpdateRoutesRequest)(nil),               // 25: sandbox.v1.UpdateRoutesRequest
	(*ListInterfacesRequest)(nil),             // 26: sandbox.v1.ListInterfacesRequest
	(*ListRoutesRequest)(nil),                 // 27: sandbox.v1.ListRoutesRequest
	(*AddARPNeighborsRequest)(nil),            // 28: sandbox.v1.AddARPNeighborsRequest
	(*GetIPTablesRequest)(nil),                // 29: sandbox.v1.GetIPTablesRequest
	(*SetIPTablesRequest)(nil),                // 30: sandbox.v1.SetIPTablesRequest
	(*GetMetricsRequest)(nil),                 // 31: sandbox.v1.GetMetricsRequest
	(*MemAgentMemcgSetRequest)(nil),           // 32: sandbox.v1.MemAgentMemcgSetRequest
	(*MemAgentCompactSetRequest)(nil),         // 33: sandbox.v1.MemAgentCompactSetRequest
	(*SetGuestDateTimeRequest)(nil),           // 34: sandbox.v1.SetGuestDateTimeRequest
	(*CopyFileRequest)(nil),                   // 35: sandbox.v1.CopyFileRequest
	(*GetVolumeStatsRequest)(nil),             // 36: sandbox.v1.GetVolumeStatsRequest
	(*ResizeVolumeRequest)(nil),               // 37: sandbox.v1.ResizeVolumeRequest
	(*grpc.CreateContainerRequest)(nil),       // 38: grpc.CreateContainerRequest
	(*grpc.StartContainerRequest)(nil),        // 39: grpc.StartContainerRequest
	(*grpc.RemoveContainerRequest)(nil),       // 40: grpc.RemoveContainerRequest
	(*grpc.ExecProcessRequest)(nil),           // 41: grpc.ExecProcessRequest
	(*grpc.SignalProcessRequest)(nil),         // 42: grpc.SignalProcessRequest
	(*grpc.WaitProcessRequest)(nil),           // 43: grpc.WaitProcessRequest
	(*grpc.UpdateContainerRequest)(nil),       // 44: grpc.UpdateContainerRequest
	(*grpc.UpdateEphemeralMountsRequest)(nil), // 45: grpc.UpdateEphemeralMountsRequest
	(*grpc.StatsContainerRequest)(nil),        // 46: grpc.StatsContainerRequest
	(*grpc.PauseContainerRequest)(nil),        // 47: grpc.PauseContainerRequest
	(*grpc.ResumeContainerRequest)(nil),       // 48: grpc.ResumeContainerRequest
	(*grpc.WriteStreamRequest)(nil),           // 49: grpc.WriteStreamRequest
	(*grpc.ReadStreamRequest)(nil),            // 50: grpc.ReadStreamRequest
	(*grpc.CloseStdinRequest)(nil),            // 51: grpc.CloseStdinRequest
	(*grpc.TtyWinResizeRequest)(nil),          // 52: grpc.TtyWinResizeRequest
	(*grpc.UpdateInterfaceRequest)(nil),       // 53: grpc.UpdateInterfaceRequest
	(*grpc.UpdateRoutesRequest)(nil),          // 54: grpc.UpdateRoutesRequest
	(*grpc.AddARPNeighborsRequest)(nil),       // 55: grpc.AddARPNeighborsRequest
	(*grpc.GetIPTablesRequest)(nil),           // 56: grpc.GetIPTablesRequest
	(*grpc.SetIPTablesRequest)(nil),           // 57: grpc.SetIPTablesRequest
	(*grpc.MemAgentMemcgConfig)(nil),          // 58: grpc.MemAgentMemcgConfig
	(*grpc.MemAgentCompactConfig)(nil),        // 59: grpc.MemAgentCompactConfig
	(*grpc.SetGuestDateTimeRequest)(nil),      // 60: grpc.SetGuestDateTimeRequest
	(*grpc.CopyFileRequest)(nil),              // 61: grpc.CopyFileRequest
	(*grpc.VolumeStatsRequest)(nil),           // 62: grpc.VolumeStatsRequest
	(*grpc.ResizeVolumeRequest)(nil),          // 63: grpc.ResizeVolumeRequest
	(*emptypb.Empty)(nil),                     // 64: google.protobuf.Empty
	(*grpc.WaitProcessResponse)(nil),          // 65: grpc.WaitProcessResponse
	(*grpc.StatsContainerResponse)(nil),       // 66: grpc.StatsContainerResponse
	(*grpc.WriteStreamResponse)(nil),          // 67: grpc.WriteStreamResponse
	(*grpc.ReadStreamResponse)(nil),           // 68: grpc.ReadStreamResponse
	(*protocols.Interface)(nil),               // 69: types.Interface
	(*grpc.Routes)(nil),                       // 70: grpc.Routes
	(*grpc.Interfaces)(nil),                   // 71: grpc.Interfaces
	(*grpc.GetIPTablesResponse)(nil),          // 72: grpc.GetIPTablesResponse
	(*grpc.SetIPTablesResponse)(nil),          // 73: grpc.SetIPTablesResponse
	(*grpc.Metrics)(nil),                      // 74: grpc.Metrics
	(*grpc.VolumeStatsResponse)(nil),          // 75: grpc.VolumeStatsResponse
}
var file_sandbox_proto_depIdxs = []int32{
	3,  // 0: sandbox.v1.ListVMsResponse.vms:type_name -> sandbox.v1.VMInfo
	38, // 1: sandbox.v1.CreateContainerRequest.request:type_name -> grpc.CreateContainerRequest
	39, // 2: sandbox.v1.StartContainerRequest.request:type_name -> grpc.StartContainerRequest
	40, // 3: sandbox.v1.RemoveContainerRequest.request:type_name -> grpc.RemoveContainerRequest
	41, // 4: sandbox.v1.ExecProcessRequest.request:type_name -> grpc.ExecProcessRequest
	42, // 5: sandbox.v1.SignalProcessRequest.request:type_name -> grpc.SignalProcessRequest
	43, // 6: sandbox.v1.WaitProcessRequest.request:type_name -> grpc.WaitProcessRequest
	44, // 7: sandbox.v1.UpdateContainerRequest.request:type_name -> grpc.UpdateContainerRequest
	45, // 8: sandbox.v1.UpdateEphemeralMountsRequest.request:type_name -> grpc.UpdateEphemeralMountsRequest
	46, // 9: sandbox.v1.StatsContainerRequest.request:type_name -> grpc.StatsContainerRequest
	47, // 10: sandbox.v1.PauseContainerRequest.request:type_name -> grpc.PauseContainerRequest
	48, // 11: sandbox.v1.ResumeContainerRequest.request:type_name -> grpc.ResumeContainerRequest
	49, // 12: sandbox.v1.WriteStdinRequest.request:type_name -> grpc.WriteStreamRequest
	50, // 13: sandbox.v1.ReadStdoutRequest.request:type_name -> grpc.ReadStreamRequest
	50, // 14: sandbox.v1.ReadStderrRequest.request:type_name -> grpc.ReadStreamRequest
	51, // 15: sandbox.v1.CloseStdinRequest.request:type_name -> grpc.CloseStdinRequest
	52, // 16: sandbox.v1.TtyWinResizeRequest.request:type_name -> grpc.TtyWinResizeRequest
	53, // 17: sandbox.v1.UpdateInterfaceRequest.request:type_name -> grpc.UpdateInterfaceRequest
	54, // 18: sandbox.v1.UpdateRoutesRequest.request:type_name -> grpc.UpdateRoutesRequest
	55, // 19: sandbox.v1.AddARPNeighborsRequest.request:type_name -> grpc.AddARPNeighborsRequest
	56, // 20: sandbox.v1.GetIPTablesRequest.request:type_name -> grpc.GetIPTablesRequest
	57, // 21: sandbox.v1.SetIPTablesRequest.request:type_name -> grpc.SetIPTablesRequest
	58, // 22: sandbox.v1.MemAgentMemcgSetRequest.request:type_name -> grpc.MemAgentMemcgConfig
	59, // 23: sandbox.v1.MemAgentCompactSetRequest.request:type_name -> grpc.MemAgentCompactConfig
	60, // 24: sandbox.v1.SetGuestDateTimeRequest.request:type_name -> grpc.SetGuestDateTimeRequest
	61, // 25: sandbox.v1.CopyFileRequest.request:type_name -> grpc.CopyFileRequest
	62, // 26: sandbox.v1.GetVolumeStatsRequest.request:type_name -> grpc.VolumeStatsRequest
	63, // 27: sandbox.v1.ResizeVolumeRequest.request:type_name -> grpc.ResizeVolumeRequest
	64, // 28: sandbox.v1.SandboxAgent.Health:input_type -> google.protobuf.Empty
	1,  // 29: sandbox.v1.SandboxAgent.ListVMs:input_type -> sandbox.v1.ListVMsRequest
	6,  // 30: sandbox.v1.SandboxAgent.Exec:input_type -> sandbox.v1.ExecRequest
	4,  // 31: sandbox.v1.SandboxAgent.SaveVMState:input_type -> sandbox.v1.SaveVMStateRequest
	5,  // 32: sandbox.v1.SandboxAgent.RestoreVMState:input_type -> sandbox.v1.RestoreVMStateRequest
	8,  // 33: sandbox.v1.SandboxAgent.CreateContainer:input_type -> sandbox.v1.CreateContainerRequest
	9,  // 34: sandbox.v1.SandboxAgent.StartContainer:input_type -> sandbox.v1.StartContainerRequest
	10, // 35: sandbox.v1.SandboxAgent.RemoveContainer:input_type -> sandbox.v1.RemoveContainerRequest
	11, // 36: sandbox.v1.SandboxAgent.ExecProcess:input_type -> sandbox.v1.ExecProcessRequest
	12, // 37: sandbox.v1.SandboxAgent.SignalProcess:input_type -> sandbox.v1.SignalProcessRequest
	13, // 38: sandbox.v1.SandboxAgent.WaitProcess:input_type -> sandbox.v1.WaitProcessRequest
	14, // 39: sandbox.v1.SandboxAgent.UpdateContainer:input_type -> sandbox.v1.UpdateContainerRequest
	15, // 40: sandbox.v1.SandboxAgent.UpdateEphemeralMounts:input_type -> sandbox.v1.UpdateEphemeralMountsRequest
	16, // 41: sandbox.v1.SandboxAgent.StatsContainer:input_type -> sandbox.v1.StatsContainerRequest
	17, // 42: sandbox.v1.SandboxAgent.PauseContainer:input_type -> sandbox.v1.PauseContainerRequest
	18, // 43: sandbox.v1.SandboxAgent.ResumeContainer:input_type -> sandbox.v1.ResumeContainerRequest
	19, // 44: sandbox.v1.SandboxAgent.WriteStdin:input_type -> sandbox.v1.WriteStdinRequest
	20, // 45: sandbox.v1.SandboxAgent.ReadStdout:input_type -> sandbox.v1.ReadStdoutRequest
	21, // 46: sandbox.v1.SandboxAgent.ReadStderr:input_type -> sandbox.v1.ReadStderrRequest
	22, // 47: sandbox.v1.SandboxAgent.CloseStdin:input_type -> sandbox.v1.CloseStdinRequest
	23, // 48: sandbox.v1.SandboxAgent.TtyWinResize:input_type -> sandbox.v1.TtyWinResizeRequest
	24, // 49: sandbox.v1.SandboxAgent.UpdateInterface:input_type -> sandbox.v1.UpdateInterfaceRequest
	25, // 50: sandbox.v1.SandboxAgent.UpdateRoutes:input_type -> sandbox.v1.UpdateRoutesRequest
	26, // 51: sandbox.v1.SandboxAgent.ListInterfaces:input_type -> sandbox.v1.ListInterfacesRequest
	27, // 52: sandbox.v1.SandboxAgent.ListRoutes:input_type -> sandbox.v1.ListRoutesRequest
	28, // 53: sandbox.v1.SandboxAgent.AddARPNeighbors:input_type -> sandbox.v1.AddARPNeighborsRequest
	29, // 54: sandbox.v1.SandboxAgent.GetIPTables:input_type -> sandbox.v1.GetIPTablesRequest
	30, // 55: sandbox.v1.SandboxAgent.SetIPTables:input_type -> sandbox.v1.SetIPTablesRequest
	31, // 56: sandbox.v1.SandboxAgent.GetMetrics:input_type -> sandbox.v1.GetMetricsRequest
	32, // 57: sandbox.v1.SandboxAgent.MemAgentMemcgSet:input_type -> sandbox.v1.MemAgentMemcgSetRequest
	33, // 58: sandbox.v1.SandboxAgent.MemAgentCompactSet:input_type -> sandbox.v1.MemAgentCompactSetRequest
	34, // 59: sandbox.v1.SandboxAgent.SetGuestDateTime:input_type -> sandbox.v1.SetGuestDateTimeRequest
	35, // 60: sandbox.v1.SandboxAgent.CopyFile:input_type -> sandbox.v1.CopyFileRequest
	36, // 61: sandbox.v1.SandboxAgent.GetVolumeStats:input_type -> sandbox.v1.GetVolumeStatsRequest
	37, // 62: sandbox.v1.SandboxAgent.ResizeVolume:input_type -> sandbox.v1.ResizeVolumeRequest
	0,  // 63: sandbox.v1.SandboxAgent.Health:output_type -> sandbox.v1.HealthResponse
	2,  // 64: sandbox.v1.SandboxAgent.ListVMs:output_type -> sandbox.v1.ListVMsResponse
	7,  // 65: sandbox.v1.SandboxAgent.Exec:output_type -> sandbox.v1.ExecResponse
	64, // 66: sandbox.v1.SandboxAgent.SaveVMState:output_type -> google.protobuf.Empty
	64, // 67: sandbox.v1.SandboxAgent.RestoreVMState:output_type -> google.protobuf.Empty
	64, // 68: sandbox.v1.SandboxAgent.CreateContainer:output_type -> google.protobuf.Empty
	64, // 69: sandbox.v1.SandboxAgent.StartContainer:output_type -> google.protobuf.Empty
	64, // 70: sandbox.v1.SandboxAgent.RemoveContainer:output_type -> google.protobuf.Empty
	64, // 71: sandbox.v1.SandboxAgent.ExecProcess:output_type -> google.protobuf.Empty
	64, // 72: sandbox.v1.SandboxAgent.SignalProcess:output_type -> google.protobuf.Empty
	65, // 73: sandbox.v1.SandboxAgent.WaitProcess:output_type -> grpc.WaitProcessResponse
	64, // 74: sandbox.v1.SandboxAgent.UpdateContainer:output_type -> google.protobuf.Empty
	64, // 75: sandbox.v1.SandboxAgent.UpdateEphemeralMounts:output_type -> google.protobuf.Empty
	66, // 76: sandbox.v1.SandboxAgent.StatsContainer:output_type -> grpc.StatsContainerResponse
	64, // 77: sandbox.v1.SandboxAgent.PauseContainer:output_type -> google.protobuf.Empty
	64, // 78: sandbox.v1.SandboxAgent.ResumeContainer:output_type -> google.protobuf.Empty
	67, // 79: sandbox.v1.SandboxAgent.WriteStdin:output_type -> grpc.WriteStreamResponse
	68, // 80: sandbox.v1.SandboxAgent.ReadStdout:output_type -> grpc.ReadStreamResponse
	68, // 81: sandbox.v1.SandboxAgent.ReadStderr:output_type -> grpc.ReadStreamResponse
	64, // 82: sandbox.v1.SandboxAgent.CloseStdin:output_type -> google.protobuf.Empty
	64, // 83: sandbox.v1.SandboxAgent.TtyWinResize:output_type -> google.protobuf.Empty
	69, // 84: sandbox.v1.SandboxAgent.UpdateInterface:output_type -> types.Interface
	70, // 85: sandbox.v1.SandboxAgent.UpdateRoutes:output_type -> grpc.Routes
	71, // 86: sandbox.v1.SandboxAgent.ListInterfaces:output_type -> grpc.Interfaces
	70, // 87: sandbox.v1.SandboxAgent.ListRoutes:output_type -> grpc.Routes
	64, // 88: sandbox.v1.SandboxAgent.AddARPNeighbors:output_type -> google.protobuf.Empty
	72, // 89: sandbox.v1.SandboxAgent.GetIPTables:output_type -> grpc.GetIPTablesResponse
	73, // 90: sandbox.v1.SandboxAgent.SetIPTables:output_type -> grpc.SetIPTablesResponse
	74, // 91: sandbox.v1.SandboxAgent.GetMetrics:output_type -> grpc.Metrics
	64, // 92: sandbox.v1.SandboxAgent.MemAgentMemcgSet:output_type -> google.protobuf.Empty
	64, // 93: sandbox.v1.SandboxAgent.MemAgentCompactSet:output_type -> google.protobuf.Empty
	64, // 94: sandbox.v1.SandboxAgent.SetGuestDateTime:output_type -> google.protobuf.Empty
	64, // 95: sandbox.v1.SandboxAgent.CopyFile:output_type -> google.protobuf.Empty
	75, // 96: sandbox.v1.SandboxAgent.GetVolumeStats:output_type -> grpc.VolumeStatsResponse
	64, // 97: sandbox.v1.SandboxAgent.ResizeVolume:output_type -> google.protobuf.Empty
	63, // [63:98] is the sub-list for method output_type
	28, // [28:63] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
