// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: storage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // Name of the file (e.g., "snapshot.tar.gz")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLRequest) Reset() {
	*x = GetUploadURLRequest{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLRequest) ProtoMessage() {}

func (x *GetUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetUploadURLRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetUploadURLRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetUploadURLResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Presigned PUT URL for uploading the file
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// S3 key where the file will be stored
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// URL expiry time in seconds
	ExpiresInSeconds int64 `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUploadURLResponse) Reset() {
	*x = GetUploadURLResponse{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLResponse) ProtoMessage() {}

func (x *GetUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GetUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetUploadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetUploadURLResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetUploadURLResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type GetDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetDownloadURLRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetDownloadURLRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetDownloadURLResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Presigned GET URL for downloading the file
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// S3 key where the file is stored
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// URL expiry time in seconds
	ExpiresInSeconds int64 `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDownloadURLResponse) Reset() {
	*x = GetDownloadURLResponse{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResponse) ProtoMessage() {}

func (x *GetDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetDownloadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetDownloadURLResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetDownloadURLResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type CheckFileExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFileExistsRequest) Reset() {
	*x = CheckFileExistsRequest{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFileExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFileExistsRequest) ProtoMessage() {}

func (x *CheckFileExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFileExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckFileExistsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *CheckFileExistsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CheckFileExistsRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type CheckFileExistsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Exists bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	// Size in bytes (0 if not exists)
	SizeBytes int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Last modified timestamp (0 if not exists)
	LastModifiedUnix int64 `protobuf:"varint,3,opt,name=last_modified_unix,json=lastModifiedUnix,proto3" json:"last_modified_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckFileExistsResponse) Reset() {
	*x = CheckFileExistsResponse{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFileExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFileExistsResponse) ProtoMessage() {}

func (x *CheckFileExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFileExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckFileExistsResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *CheckFileExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckFileExistsResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CheckFileExistsResponse) GetLastModifiedUnix() int64 {
	if x != nil {
		return x.LastModifiedUnix
	}
	return 0
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFileResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\n" +
	"storage.v1\"Q\n" +
	"\x13GetUploadURLRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"h\n" +
	"\x14GetUploadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x03R\x10expiresInSeconds\"S\n" +
	"\x15GetDownloadURLRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"j\n" +
	"\x16GetDownloadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x03R\x10expiresInSeconds\"T\n" +
	"\x16CheckFileExistsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"~\n" +
	"\x17CheckFileExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12,\n" +
	"\x12last_modified_unix\x18\x03 \x01(\x03R\x10lastModifiedUnix\"O\n" +
	"\x11DeleteFileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xe5\x02\n" +
	"\x0eStorageService\x12Q\n" +
	"\fGetUploadURL\x12\x1f.storage.v1.GetUploadURLRequest\x1a .storage.v1.GetUploadURLResponse\x12W\n" +
	"\x0eGetDownloadURL\x12!.storage.v1.GetDownloadURLRequest\x1a\".storage.v1.GetDownloadURLResponse\x12Z\n" +
	"\x0fCheckFileExists\x12\".storage.v1.CheckFileExistsRequest\x1a#.storage.v1.CheckFileExistsResponse\x12K\n" +
	"\n" +
	"DeleteFile\x12\x1d.storage.v1.DeleteFileRequest\x1a\x1e.storage.v1.DeleteFileResponseBHZFgithub.com/cohere-ai/kata-containers/src/sandbox-service/pkg/api/pb;pbb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_storage_proto_goTypes = []any{
	(*GetUploadURLRequest)(nil),     // 0: storage.v1.GetUploadURLRequest
	(*GetUploadURLResponse)(nil),    // 1: storage.v1.GetUploadURLResponse
	(*GetDownloadURLRequest)(nil),   // 2: storage.v1.GetDownloadURLRequest
	(*GetDownloadURLResponse)(nil),  // 3: storage.v1.GetDownloadURLResponse
	(*CheckFileExistsRequest)(nil),  // 4: storage.v1.CheckFileExistsRequest
	(*CheckFileExistsResponse)(nil), // 5: storage.v1.CheckFileExistsResponse
	(*DeleteFileRequest)(nil),       // 6: storage.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),      // 7: storage.v1.DeleteFileResponse
}
var file_storage_proto_depIdxs = []int32{
	0, // 0: storage.v1.StorageService.GetUploadURL:input_type -> storage.v1.GetUploadURLRequest
	2, // 1: storage.v1.StorageService.GetDownloadURL:input_type -> storage.v1.GetDownloadURLRequest
	4, // 2: storage.v1.StorageService.CheckFileExists:input_type -> storage.v1.CheckFileExistsRequest
	6, // 3: storage.v1.StorageService.DeleteFile:input_type -> storage.v1.DeleteFileRequest
	1, // 4: storage.v1.StorageService.GetUploadURL:output_type -> storage.v1.GetUploadURLResponse
	3, // 5: storage.v1.StorageService.GetDownloadURL:output_type -> storage.v1.GetDownloadURLResponse
	5, // 6: storage.v1.StorageService.CheckFileExists:output_type -> storage.v1.CheckFileExistsResponse
	7, // 7: storage.v1.StorageService.DeleteFile:output_type -> storage.v1.DeleteFileResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
