{{- if .Values.sandboxAgent.enabled }}
{{- $name := printf "%s-sandbox-agent" .Chart.Name -}}
{{- if .Values.env.multiInstallSuffix }}
{{- $name = printf "%s-%s" $name .Values.env.multiInstallSuffix -}}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sandbox-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: sandbox-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: sandbox-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sandbox-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sandbox-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 9090
      protocol: TCP
      targetPort: grpc
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sandbox-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sandbox-agent
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sandbox-agent
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ $name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sandbox-agent
          image: {{ .Values.sandboxAgent.image.reference }}:{{ default .Chart.AppVersion .Values.sandboxAgent.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - --http-addr=:8080
            - --grpc-addr=:9090
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: shim-sockets
              mountPath: /run/vc/sbs
              readOnly: true
            - name: shim-sockets-rs
              mountPath: /run/kata
              readOnly: true
            - name: containerd-sock
              mountPath: /run/containerd
              readOnly: true
      volumes:
        - name: shim-sockets
          hostPath:
            path: /run/vc/sbs
            type: DirectoryOrCreate
        - name: shim-sockets-rs
          hostPath:
            path: /run/kata
            type: DirectoryOrCreate
        - name: containerd-sock
          hostPath:
            path: /run/containerd
            type: Directory
{{- end }}
